### ISSUE TITLE
Support overriding naming for columns globally (e.g snake_case, camelCase, exact property name, etc...)

### ISSUE THREAD

**Issue by JoseGeorges8** [simolus3/drift#1068]
**Is your feature request related to a problem? Please describe.**
I need to make my column names to be the same as my property names, but using named in each column for each table can be tedious and prone to error by not adding it

**Describe the solution you'd like**
add an option to let moor know I want my column names to be created in a specific manner globally.

**Comment by simolus3** [comment]
Do you really need camel case or just the exact names you're using in Dart?

**Comment by JoseGeorges8** [comment]
the exact names I'm using in dart

**Comment by JoseGeorges8** [comment]
I've updated the title and description
