### ISSUE TITLE
Thank you :)

### ISSUE THREAD

**Issue by monolidth** [simolus3/drift#1123]
I don't have any issue with the library. I only appreciate the work you have done.

Regards,
William

**Comment by kuhnroyal** [comment]
@simolus3 You should pin this!

**Comment by Mike278** [comment]
Ditto!

**Comment by davidmartos96** [comment]
👌

**Comment by simolus3** [comment]
Thank you all :blush: :heart:

**Comment by Juliotati** [comment]
```dart
void main() {
  final String message = '@simolus3, @juliotati is 100B% gratefull!';
  print(message);
}
```

**Comment by gloryluu** [comment]
This is a cool lib and most of all, I love your active supporting @simolus3 . Thank you so much.

**Comment by gsouf** [comment]
Moor is really well designed and pleasant to use, it makes persistence in flutter apps a lot funnier than it could be without. I'm looking forward to have a chance to give contribution to the library. 🤏🏽

**Comment by mattsimgithub** [comment]
Agreed, this is very good software, very well maintained. Thanks for all the work you do.

**Comment by pratikbutani** [comment]
Lovely work ❤

**Comment by NaarGes** [comment]
I'm working with this package in about two years and I'm so pleased with it and with your support, availability and hard work. Thank you so much! ❤

**Comment by II11II** [comment]
Thank you for making Dart popular for the backend across other languages by creating this libary.
You are the best😎
@simolus3

**Comment by matecode** [comment]
❤

**Comment by JCKodel** [comment]
I think there is an important feature missing in this library: a Donate/Sponsor it button!

**Comment by pomid** [comment]
❤

**Comment by FaFre** [comment]
Hello @simolus3,

thank you so much for providing this library (and sqlite3). It is amazing how much value you created here. It is build up so stable on a concrete base with years of experience (sql parser etc.). Your constant efforts and maintenance are remarkable and really outstanding, pushing the library further and further. It's just incredible. I'm using drift for a few projects now and are always amazed by its magic.

Thank you ❤

**Comment by galacticgibbon** [comment]
This package is pure magic. You are the man
