### ISSUE TITLE
Remove SqlTypeSystem

### ISSUE THREAD

**Issue by simolus3** [simolus3/drift#1158]
Currently, moor uses the `SqlTypeSystem` class which describes how to map Dart values from and to values understood by the database. This works, but has proven to be overly complex and expensive:

- it was supposed to support custom types, but those were realized through type converters
- looking up the right type for each mapped column at runtime is expensive (the generator can turn this into a static call)
- integration into Dart's null safe typesystem is mediocre
- custom type systems are not supported by isolates

I think we can remove that class and the `SqlType` classes, replacing them with static methods to transform values. The class will be deprecated in the next moor release and removed in the next major version bump.

Related todos:

- Remove the database parameter from generated `fromData` methods on data classes, it's no longer necessary (but breaking to remove)
- (#1556): Don't expect the converted type in the custom companion constructor.

**Comment by NicolaVerbeeck** [comment]
@simolus3 I see in `sql_types.dart` that we should use SqlTypeSystem instead. Yet here you state that this is going to be removed.

If you remove the SqlType classes, inspector tools like drift_inspector (and a soon to be announced new tool to replace it) will not be able to extract type information from the `GeneratedColumn` classes required to build comprehensive tools. 

Please keep this in mind when removing identifiable column type information from the library 🙏

**Comment by simolus3** [comment]
Thanks for your work on drift_inspector and your feedback! At the moment, we have a `typeName` field on generated columns, giving you the type of the column at runtime, is that enough for your use case or are you looking for more?

Initially, the type system was there so that the mapping of values could be configured, but type converters are a cleaner solution to that problem and it's more efficient to sidestep this mechanism in some cases. This is why I want to remove it entirely (it doesn't have much use at the moment inside of drift). Obviously if there's specific information you need for inspectors that we're not providing outside of deprecated classes, I want to change that ^^

**Comment by NicolaVerbeeck** [comment]
If I recall correctly, I just moved away from typeName since it is marked as deprecated 😂

**Comment by simolus3** [comment]
Oh right, `type.sqlName()` is is then :D That one _is_ used by drift though, so there'll be a replacement if `SqlType`s are going.

**Comment by NicolaVerbeeck** [comment]
I could use that for now. Though that loses some context about some fine grained info such as: bools and datetimes. 

I guess I'll keep it as-is for now and when the breaking change finally happens, look as to what I can use instead (I used to use `column is GeneratedColumn<bool>` 😅)

**Comment by simolus3** [comment]
This is done now.

@NicolaVerbeeck In the upcoming drift 2.0 release, you will be able to use `GeneratedColumn.type` which is now an enum over all supported drift types. So hopefully it's even nicer to use than matching type names represented as a string :)

In addition, in drift 2.0 it will be possible two switch between two storage modes for datetimes (the current unix timestamps as integer mode and a text-based mode). You can use `databaseInstance.options.types.storeDateTimesAsText` to check which mode is active (and generally use `databaseInstance.options.types.read` to map a column from SQL to Dart now.

If you run into any issues migrating to drift 2.0 (not released yet), please let me know. Thanks for all your work on the local storage inspector!

**Comment by NicolaVerbeeck** [comment]
@simolus3 What is the time frame for release 2.0? I will start working after my holidays

**Comment by simolus3** [comment]
My rough estimate is "sometime this month". I have most of the breaking changes I want in, but I still need to do some testing and proof-reading for the documentation. So no reason to be in a hurry, I just wanted to give an early heads-up :)
