### ISSUE TITLE
Generate sql parameters index  error

### ISSUE THREAD

**Issue by YeungKC** [simolus3/drift#1496]
sql:

```sql
select * from foo where a = :a AND b in :b AND c = :c;
```

generate code:

```dart
    var $arrayStartIndex = 2;
    final expandedcategories = $expandVar($arrayStartIndex, categories.length);
    $arrayStartIndex += categories.length;
    customSelect('select * from foo where a = ?1 AND b in ($expandedcategories) AND c = ?2;') // bug!!!!
....
```

If the "in parameter" order is not the last, the parameters index will be repeated.

**Comment by simolus3** [comment]
Good catch, thank you! 

Initially my idea was to stop generating explictly indexed variables with the new code generation option, but that wouldn't work as the new generator re-orders variables in some cases.

Instead, I changed the generator to instead use explicitly-indexed variables everywhere, putting regular variables first. With 6bcb0070b0f5116c0bca966b89c1dad7fedffe0d, your query should be generated as

```dart
    var $arrayStartIndex = 3;
    final expandedcategories = $expandVar($arrayStartIndex, categories.length);
    $arrayStartIndex += categories.length;
    customSelect('select * from foo where a = ?1 AND b in ($expandedcategories) AND c = ?2;')
```
