### ISSUE TITLE
Bad state: Tried to send Request ... over isolate channel, but the connection was closed!

### ISSUE THREAD

**Issue by Raluca1** [simolus3/drift#1516]
Hello,

We have a persistent type of crash recorded in Instabug, that appears every day, on various versions of our Flutter app.

This type of crash can be traced back to moor version 4.2.1, and now we are working with the latest moor version ^4.6.1.

The error is like below, with f1, f2, f3 denoting field names in a table and v1, v2, v3 values to be inserted in the table:

>```Bad state: Tried to send Request (id = 407): StatementMethod.insert: INSERT INTO table_name (f1, f2, f3) VALUES (?, ?, ?) ON CONFLICT(f1, f3) DO UPDATE SET f1 = ?, f2 = ?, f3 = ? with [v1, v2, v3, v1, v2, v3] over isolate channel, but the connection was closed!```

The stacktrace as reported by Instabug is:

```
0   DriftCommunication._send    package:drift/src/remote/communication.dart:107
1   DriftCommunication.request  package:drift/src/remote/communication.dart:101
2   _BaseExecutor._runRequest   package:drift/src/remote/client_impl.dart:72
3   _BaseExecutor.runInsert package:drift/src/remote/client_impl.dart:99
4   InsertStatement.insert.<fn> package:drift/src/runtime/query_builder/statements/insert.dart:70
5   InsertStatement.insert.<fn> package:drift/src/runtime/query_builder/statements/insert.dart:69
6   DatabaseConnectionUser.doWhenOpened.<fn>    package:drift/src/runtime/api/connection_user.dart:154
7   _rootRunUnary   dart:async/zone.dart:1436
8   _CustomZone.runUnary    dart:async/zone.dart:1335
9   InsertStatement.insert  package:drift/src/runtime/query_builder/statements/insert.dart:69
```

Have you seen these errors before? What can be done about them? 

Thank you!

**Comment by Raluca1** [comment]
Thank you for your reply. Yes, `shutdownAll` is called when the user is logout, but the exceptions are caught.

**Comment by Raluca1** [comment]
Is there a way to register a Drift exception handler, so that an unhandled error is not propagated all the way to Flutter framework?

**Comment by simolus3** [comment]
You can use [`runZonedGuarded`](https://api.dart.dev/stable/2.14.4/dart-async/runZonedGuarded.html) to add an exception handler around a block of code (including async code), but Drift doesn't provide anything like that.

I'm still not entirely sure what could have caused this in the first place. It kind of looks like you're using a database after closing it, but maybe this happens across isolates? E.g.

1. Isolate A runs `shutdownAll`
2. In parallel, Isolate B is still using the database

Or are you only using drift in one main isolate?

**Comment by dickermoshe** [comment]
This thread has not had any activity in over a year. Closing...
