### ISSUE TITLE
Custom Instance Variables on Table Classes

### ISSUE THREAD

**Issue by Rossdex** [simolus3/drift#1676]
I am currently in the process of writing a large scale app with the option for multiple join queries. 

After looking at your join example I decided rather than making a custom class for each of the joins I would make custom row classes for each of my table models that had the joins as optional instance variables. e.g. the users list on the below company class.

```
class Company {
  final int id;
  final int? currentUserId;
  final int synced;
  final int syncAttempts;
  final String title;
  final String address1;
  final String? address2;
  final String postcode;
  late List<User> users;  // can be defaulted to an empty list rather than called late
  Company({
    required this.id,
    this.currentUserId,
    required this.synced,
    required this.syncAttempts,
    required this.title,
    required this.address1,
    this.address2,
    required this.postcode,
  });
}
```

My thinking is this allows for much more consistent front-end code where if you have a company model, you can easily ask for the users in the join and always get the company with it's users. This allows the company model to have other joins on the same class, for example a company may have a list of venues which we may need to show on the same page as it's users. 

This has meant that I have to not only make a table model but also a custom row class for each of my tables. 

Would it be possible for the auto generated row class to have these extra, `none column` variables that can be filled in during a custom map function called after the watchSingle or getSingle functions? 

```
queryStream.map(
  (event) {
      Company company = event.readTable(db.companies);
      company.users = event.readTableOrNull(db.users);
      company.venues= event.readTableOrNull(db.venues);
      return company;
  },
);
```

**Comment by simolus3** [comment]
This will be part of the next drift release.
