### ISSUE TITLE
Generated field of an View DataClass is not nullable

### ISSUE THREAD

**Issue by RalphBergmannKMB** [simolus3/drift#1719]
I have this table and have filled it with some data:

```sql
CREATE TABLE IF NOT EXISTS foobar
(
    foo TEXT,
    bar TEXT
);

INSERT INTO foobar (foo, bar) VALUES ('foo 1', 'bar 2');
INSERT INTO foobar (foo, bar) VALUES ('foo 2', NULL);
```

A select with concatenation has this result:

```sql
SELECT foo, bar, foo || ' ' || bar FROM foobar;
```

| foo | bar | foo \|\| ' ' \|\| bar |
| :--- | :--- | :--- |
| foo 1 | bar 2 | foo 1 bar 2 |
| foo 2 | NULL | NULL |

Now when I use this select statement to create a view in a drift file, the created field `foobar` must be nullable, but it isn't:

```sql
CREATE VIEW IF NOT EXISTS foobarview AS
SELECT foo, bar, foo || ' ' || bar as foobar FROM foobar;
```

```dart
class FoobarviewData extends DataClass {
  final String? foo;
  final String? bar;
  final String foobar;
  FoobarviewData({this.foo, this.bar, required this.foobar});

...
```

**Comment by simolus3** [comment]
Thanks for the report and the very helpful repro! I've fixed this in 9c80fb047b579eca0811be0d81bf78bc2da280f3.
