### ISSUE TITLE
Export schema - automatically name schema file based on schemaVersion

### ISSUE THREAD

**Issue by North101** [simolus3/drift#1721]
When exporting the file you shouldn't need to name the file, just the directory.

The naming convention is hard coded so it should just pull the schemaVersion from the database file.

**Comment by simolus3** [comment]
Good idea, done!

**Comment by North101** [comment]
Just tried it and it worked great. I can now put this into my build script. Thanks!

**Comment by kuhnroyal** [comment]
Nice idea!
