### ISSUE TITLE
Help needed .NoSuchMethodError: The method 'unary-' was called on null.

### ISSUE THREAD

**Issue by inzkhan** [simolus3/drift#1723]
HI,First of all thanks for this amazing plugin.Currently i am facing an issue whenever i try to insert value inside the database ,I got this exception.Can you elaborate what thing is causing this issue.Thanks
```
I/flutter (14509): Drift: Sent INSERT INTO churn_metric (saved_value, current_value, difference, metric_saved_at) VALUES (?, ?, ?, ?) with args [50.0, 100.0, 222.0, 1646302998]
E/flutter (14509): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The method 'unary-' was called on null.
E/flutter (14509): Receiver: null
E/flutter (14509): Tried calling: unary-()
E/flutter (14509): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (14509): #1      _VmDelegate.runInsert
package:drift/…/ffi/database.dart:219
E/flutter (14509): <asynchronous suspension>
E/flutter (14509): #2      InsertStatement.insert.<anonymous closure>
package:drift/…/statements/insert.dart:74
E/flutter (14509): <asynchronous suspension>
E/flutter (14509): #3      InsertStatement.insert
package:drift/…/statements/insert.dart:73
E/flutter (14509): <asynchronous suspension>
```

**Comment by simolus3** [comment]
The exception is a bit weird since drift is migrated to null safety (so these errors shouldn't happen) and since there is no unary minus on line 219 of `_VmDelegate`. Are you hitting this consistently? Both in debug and release mode? Can you post the exact drift version from your `.dart_tool/package_config.json` please?

**Comment by inzkhan** [comment]
Thanks for the response.Current version is 1.4.0.
I am getting this error consistently.I tested it in debug mode only.It was working fine yesterday.
![drift](https://user-images.githubusercontent.com/33628287/156569840-99f7fbfc-4098-4135-abb1-203e7da7e789.png)

**Comment by simolus3** [comment]
Is your app running with null safety? I don't really understand where the error is coming from. Does `flutter clean` do anything?

**Comment by inzkhan** [comment]
Yeah. My app is running with sound null safety. didn't try. flutter clean yet.

**Comment by inzkhan** [comment]
@simolus3  after running "pub get clean" .Now inserting is working fine but i still cant find real cause but atleast it works.

**Comment by simolus3** [comment]
Yeah given that there is no unary minus at the line specified, I assume this may be something in the compiler or in the package cache going wrong
