### ISSUE TITLE
Using custom separator in `groupConcat` when creating View

### ISSUE THREAD

**Issue by myacera100** [simolus3/drift#1729]
I'm trying to define a view by extending an abstract class from `View` following the example given in documentation. There are two expression getters declared using `groupConcat` with custom separator `$`; during debug running, an exception was reported `Unhandled Exception: SqliteException(1): parameters are not allowed in views` and after checking the sql statements following the exception line, I found the `GROUP_CONCAT` function was issued using one parameter as shown in the capture. This is conflicting as custom separator is supported by drift while the implementation is not allowed by sqlite.

<img width="748" alt="屏幕截图 2022-03-05 075725" src="https://user-images.githubusercontent.com/81943962/156858256-e0cf3993-86e9-4689-9f9c-43c334308a89.png">

**Comment by simolus3** [comment]
Thanks for the report! This is fixed in 4ddbed5ccad989386647e82b04a1254f68df3a53.
