### ISSUE TITLE
Missing libsqlite3.so

### ISSUE THREAD

**Issue by morzan1001** [simolus3/drift#1733]
Hi, I am using a Gitlab CI pipeline to run unit tests of an app that uses a drift database. The pipeline uses the Docker image [cirrusci/flutter](https://hub.docker.com/r/cirrusci/flutter/tags). Unfortunately, all tests of the database fail because the library `libsqlite3.so` cannot be loaded. The behavior is fairly new, so far this has never been a problem, so I suspect it is related to the update to `drift 1.4.0` or to the update to `flutter 2.10.3` I did recently.

The error message of the test looks exemplary as follows: 
```
{"testID":3,"error":"Invalid argument(s): Failed to load dynamic library 'libsqlite3.so': libsqlite3.so: cannot open shared object file: No such file or directory","stackTrace":"dart:ffi                                                        new DynamicLibrary.open\npackage:sqlite3/src/load_library.dart 27:29                     _defaultOpen\npackage:sqlite3/src/load_library.dart 122:12                    OpenDynamicLibrary.openSqlite\npackage:sqlite3/src/api/sqlite3.dart 10:38                      sqlite3\npackage:drift/src/ffi/database.dart 172:13                      _VmDelegate._createDatabase\npackage:drift/src/ffi/database.dart 148:7                       _VmDelegate.open\npackage:drift/src/runtime/executor/helpers/engines.dart 301:22  DelegatedDatabase.ensureOpen.<fn>\n","isFailure":false,"type":"error","time":16082}
```

This error was generated by the call:
```
flutter test --machine --coverage
```

In my `pubspec.yaml` I have defined the following packages: 
```
drift: ^1.4.0
sqlite3_flutter_libs: ^0.5.2
drift_dev: ^1.4.0
build_runner: ^2.1.7
```

To run tests I don't use a native database from Drift but an InMemory database, the factory looks like this:
```
/// This is a special factory to allow unit tests with an in memory database
  factory AppDatabase.inMemory(QueryExecutor e) {
    return AppDatabase._internal(e);
  }
```

A test call of this database then looks like the following: 
```
setUp(() {
    testDb = AppDatabase.inMemory(NativeDatabase.memory());
```

I hope someone has an idea where the problem could be, the error occurs unfortunately only recently without that I have made major changes to this code. Thanks already

**Comment by simolus3** [comment]
Maybe a change to the Dockerfile caused sqlite3 to no longer be installed by default? On Linux, `package:sqlite3` (which drift depends on for the `NativeDatabase`) uses the sqlite3 library from the system and doesn't provide its own.

Can you run  `apt install libsqlite3-dev` in your CI before you run tests and see if that fixes the problem?

**Comment by morzan1001** [comment]
Hi, thanks for the quick reply. I have indeed changed the Docker image to use the latest Flutter version in my pipeline. I just tested your suggestion briefly and with a manual install of `libsqlite3-dev` everything works again. It seems that cirrusci removed the library from the image. Thanks in any case for the help, my pipeline is running again.  👍

**Comment by SungHyun22** [comment]
@simolus3  I have a same issue. I tried "apt install libsqlite3-de" but it doesn't work for me.

my environment
- circleci
- cirrusci/flutter

**Comment by SungHyun22** [comment]
I fixed this issue. use this command.

```
 sudo apt-get update && sudo apt-get install -y sqlite3 libsqlite3-dev
```

**Comment by vanlooverenkoen** [comment]
Getting the same error. I am trying to make a dockerfile that packages my server app. But I also get this:
```
Failed to load dynamic library 'libsqlite3.so': libsqlite3.so: cannot open shared object file: No such file or directory
```

Can someone share me the Dockerfile itself that was used to fix this? Because all suggestions did not work for me

**Comment by vanlooverenkoen** [comment]
```
FROM dart:2.19.2 AS build

COPY backend/pubspec.* ./
COPY shared/ ./

COPY /backend/resources/locales.json /resources/locales.json
COPY /backend/resources/web/ /bin/web

RUN dart pub get

COPY . .
RUN cd backend && dart pub get
RUN dart compile exe backend/bin/server_prod.dart -o /bin/server

###
FROM alpine:3.17.2

RUN apk update && apk upgrade
RUN apk add --no-cache sqlite

COPY --from=build /resources/locales.json /app/resources/locales.json
COPY --from=build /bin/web/ /app/bin/web
COPY --from=build /runtime/ /
COPY --from=build /bin/server /app/bin/server

ENV JWT_SECRET=your-very-secret-key

# Start server.
EXPOSE 8080
CMD ["/app/bin/server"]

```

I see that sqlite3 is available but I still get the same error.

I triedthis:

```
open.overrideFor(OperatingSystem.linux, _openOnLinux);

DynamicLibrary _openOnLinux() {
  final libraryNextToScript = File(join('usr', 'bin', 'sqlite3'));
  return DynamicLibrary.open(libraryNextToScript.path);
}

```

and got this error:
```
Failed to load dynamic library 'usr/bin/sqlite3': usr/bin/sqlite3: cannot dynamically load position-independent executable
```
