### ISSUE TITLE
improve lower() + upper() return type on optional columns

### ISSUE THREAD

**Issue by LewisHolliday** [simolus3/drift#1735]
**```lower()```** will currently return an ```Expression<String>``` on a ```GeneratedColumn<String?>```
This prevents comparing the expression to a dart optional.

Ideally, calling lower() on a nullable column would return an ```Expression<String?>``` **?**
In where and on clauses this could allow:
```dart 
myTable.myNullableColumn.lower().equals(someOptionalValue)

**Comment by simolus3** [comment]
Good point, thanks! Fixed in 8bccc14296b4d1fd8a519bda0b32f2ace46e92f0 (there's no harm in always making it nullable).

You can also use `myTable.myNullableColumn.lower().dartCast<String?>.equals(someOptionalValue)` in the meantime.
