### ISSUE TITLE
Drift schema generates invalid code when column names only differ with leading underscore

### ISSUE THREAD

**Issue by reinhardbluelab** [simolus3/drift#1739]
For a database with 2 columns named _id_ and __id_ (I know, I know, but unfortunately not under my control) the Drift schema generates 2 class members where both are named _id_. This obviously results in a build error when trying to build the test code. 

I'm trying to follow the instructions at https://github.com/simolus3/drift/tree/latest-release/extras/migrations_example to write unit tests for database migration, but the generated Dart files are not valid.

The table class contains this:

```
IntColumn get id => integer().withDefault(const Constant(0))();

@JsonKey('_id')
TextColumn get uid => text().named('_id')();
```

 The generated class (using `dart run drift_dev schema generate`) contains this:

```
  final String id;
  final int id;
```

Using: Drift 1.4.0

**Comment by simolus3** [comment]
Good catch, thanks! I've fixed this in b25921a3627ebde9ed80b38f043287371c02b590. Unfortunately this requires adding more information to schema files, so the generation will still fail for old versions. You can manually add `"getter_name": "uid"` to the `"name": "_id"` column in your existing schema files to fix this too.
