### ISSUE TITLE
Incompatible with libsqlcipher latest version? 

### ISSUE THREAD

**Issue by simplepad** [simolus3/drift#1748]
Trying to launch the app on arch linux results in a crash, through some investigation I found that linking debian stable version of libsqlcipher (3.4.1) allows the app to run, so my question is, is libsqlcipher 4.5.1 (latest) not supported by this package?

**Comment by davidmartos96** [comment]
SQLCipher version 3.x is incompatible with 4.x. So if you try to open a database encrypted in different versions, it will not work

**Comment by simplepad** [comment]
nope, tried cleaning data dirs to force database to be created with the newer version, still crashes

**Comment by simolus3** [comment]
I'm using SQLCipher version 4.5.0-1 from the Manjaro packages and everything is working as expected. I'm using

```dart
import 'dart:ffi';
import 'package:sqlite3/open.dart';

void main() async {
  open.overrideFor(
      OperatingSystem.linux, () => DynamicLibrary.open('libsqlcipher.so'));
  // ...
}
```

Can you post the exception you're getting or more details on how we might be able to reproduce this?

**Comment by simplepad** [comment]
looks like with `isolate.connect(isolateDebugLog: true);` the only thing it returns before crash is
`flutter: [OUT]: Request (id = 0): EnsureOpen(8, null)`

**Comment by simolus3** [comment]
Do you get a more helpful error message when not using a drift isolate?

**Comment by simplepad** [comment]
Unfortunately, no.

**Comment by simolus3** [comment]
Ouch, ok. Is there a native crash happening (does Flutter just exit with 0)? Or is there a way for you to share a small project with the same issue? From my view at the tests it looks like everything's working, so I'm afraid I can't really help without more information or something to try out.

**Comment by simplepad** [comment]
It crashes with segfault, as for the implementation, as far as I can see it is written almost exactly as it shows in the wiki example for isolates (https://drift.simonbinder.eu/docs/advanced-features/isolates/).

**Comment by simolus3** [comment]
Sorry for the slow response on this. Unfortunately, I think I'll need something that's clearer to reproduce (a Dockerfile installing the sqlcipher version that doesn't work perhaps). I'm also following that page with the latest sqlcipher on Manjaro and everything works as intended.

**Comment by PhantomKnight287** [comment]
Hey @simplepad, were you able to resolve this issue?
