### ISSUE TITLE
migration tool not working on moor_flutter

### ISSUE THREAD

**Issue by Lootwig** [simolus3/drift#1753]
Running "flutter pub run moor_generator migrate" on a project changes only the pubspec.yaml and swaps out the "moor_generator" dependency with "drift_dev".

Neither the moor_flutter dependency, nor any .dart files are being changed.

When trying to migrate manually, it seems that the migration steps also don't exactly apply to flutter projects - e.g. there doesn't seem to be an implementation of "FlutterQueryExecutor" in the Drift package, but there are also no steps given on how to change this.

Am I missing any parameters for the command line tool, or are there other reasons nothing really gets migrated correctly?

**Comment by simolus3** [comment]
> Neither the moor_flutter dependency, nor any .dart files are being changed.

The  `moor_flutter` dependency doesn't have a replacement yet, but it also works with drift just fine. The migrator should replace usages of `@UseMoor` with `@DriftDatabase` though, I'll take a look at what's happening there.

I'll also setup a `drift_sqflite` package to replace `moor_flutter`, this confusion isn't helping anybody :D

**Comment by simolus3** [comment]
I've published the `drift_sqflite` package that contains `SqfliteQueryExecutor`, the replacement for `FlutterQueryExecutor`. Together with the core `drift` package, these packages replace `moor_flutter`.

I can't reproduce the issue about no Dart sources being changed though. I've copied the sources from `moor_flutter/example` in this repo to `drift_sqflite/example` in this repo, ran `moor_generator migrate` and all of the usages have been replaced.

Even after replacing `moor_generator` with `drift_dev`, you can run `flutter pub run drift_dev migrate` again to finish the migration. But be sure you're on `drift_dev` version `1.5.1`, which is the first one to recognize `moor_flutter` in the migrate command. I've also updated [the docs](https://drift.simonbinder.eu/name/) on the name change to point out the replacement for `moor_flutter`.

I hope this makes the situation much clearer. If that still doesn't work for you, or if you have more questions on how to migrate from `moor_flutter` to `drift` + `drift_sqflite`, please let me know!
