### ISSUE TITLE
WebDatabase Persistence

### ISSUE THREAD

**Issue by vicenterusso** [simolus3/drift#1754]
Trying to develop in web ambient (just for development), and I noticed that WebDatabase works nice, but after the browser closes, the database also gets deleted.

Is this the expected behaviour? Tried default (localstorage) and IndexedDB

Edit: tried with fixed port, still no persistence

**Comment by simolus3** [comment]
Could this be something on your browser? Both local storage and IndexedDB shouldn't clear themselves when the browser is restarted, or at least I've not seen them do that on my browser. Perhaps you have some extension or setting that clears data for you?

**Comment by vicenterusso** [comment]
I will make some more tests. BTW, I'm on linux, running with `fvm flutter run -d chrome` and using Brave as browser.

**Comment by simolus3** [comment]
Perhaps you have any of [this](https://community.brave.com/t/delete-file-system-and-local-storage-on-exit/71480) enabled? I can try using Brave too but it would surprise me it if it did that by default...
