### ISSUE TITLE
When overriding tableName in Table class, DataClass for table is not generated

### ISSUE THREAD

**Issue by mateoKutnjak** [simolus3/drift#1765]
UserEntity class not existant in database.g.dart when tableName is set in subclass of Table

`@DataClassName("UserEntity")
class Users extends Table {
  IntColumn get localId => integer().autoIncrement()();
  IntColumn get id => integer().customConstraint('UNIQUE')(); // * this is non-nullable for user only because user cannot be created offline without remote id
  DateTimeColumn get dateJoined => dateTime()();
  TextColumn get username => text().withLength(min: 1, max: DJANGO_SERVER_USERNAME_MAX_LENGTH)();
  TextColumn get email => text().withLength(min: 0, max: DJANGO_SERVER_EMAIL_MAX_LENGTH)();
  TextColumn get state => text().withLength(max: 1)();

  @override
  String? get tableName => "users";
}`

**Comment by simolus3** [comment]
There's an example in this repo that generates just fine:

https://github.com/simolus3/drift/blob/fcc7e42d23af2850dbe991f59313b49ed1418fa0/drift/test/data/tables/todos.dart#L13-L24

Is there any warning generated when you run the build?

**Comment by mateoKutnjak** [comment]
I started using @UseRowClass decorator and problem disappeared. If somebody has similar problem I will see what happened. For now I will close the issue.

**Comment by mateoKutnjak** [comment]
Now Companion classes are missing. UserEntity is not a problem since it is class written by me using @UseRowClass decorator. I was using name property from enum (EnumClass.type1.name) instead of string literal ("tableName"). That was causing the problem.
