### ISSUE TITLE
drift build runner runs out of scope 

### ISSUE THREAD

**Issue by egyleader** [simolus3/drift#1771]
**Describe the bug**
I currently have errors in my project as the migration form sqflite to drift is still wip ,, so I tried to run the `flutter pub run build_runner build` with the " --build-filter " flag to specify certain folder to run into ,, and it worked at first but now it gives me an error from a file that is supposed to be out of the scope of the specified folder .. no errors in the specified folder thou rather than the `part 'tables.g.dart';`

**command**

```bash
flutter pub run build_runner build --build-filter lib/core/services/database/
```

**error output**

```dart
[INFO] Generating build script...
[INFO] Generating build script completed, took 431ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 149ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 874ms

[INFO] Running build...
[INFO] Running build completed, took 28ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 113ms

[SEVERE] drift_dev:drift_dev on lib/core/services/database.dart (cached):

This builder requires Dart inputs without syntax errors.
However, package:screenmaker/core/services/database.dart (or an existing part) contains the following errors.
database.dart:108:3: Can't have modifier 'static' here.
database.dart:144:3: Can't have modifier 'static' here.
database.dart:183:1: Expected to find '}'.
And 11 more...

Try fixing the errors and re-running the build.

[SEVERE] Failed after 161ms
```

**Comment by simolus3** [comment]
I don't think this is drift's fault, the `build_runner` packages decides on which inputs to run a builder and here it decided to run `drift_dev` on `lib/core/services/database.dart`.

I wasn't aware of the `--build-filter` functionality, but maybe it does some prefix matching and somehow matches the `database.dart` file too? Does `--build-filter lib/core/services/database/**` work maybe?

My usual approach for this is to create a `build.yaml` file:

```yaml
targets:
  $default:
    builders:
      drift_dev:
        generate_for: ['lib/core/services/database/*.dart']
```
