### ISSUE TITLE
sqlite3.dll is missing.

### ISSUE THREAD

**Issue by Vedsaga** [simolus3/drift#1776]
Getting this on windows **flutter: Invalid argument(s): Failed to load dynamic library 'sqlite3.dll': error code 126* this issue exactly similar to #418. I hope it get fixed.

I hope in later version `sqlite3.dll` can come pre-bundle with drift package if it's possible.

**Comment by simolus3** [comment]
The solution is described in the issue you linked, but I've also opened https://github.com/simolus3/sqlite3.dart/issues/82 to track bundling sqlite3 across platforms.
