### ISSUE TITLE
The need for a "fallback to destructive mode" in web mode.

### ISSUE THREAD

**Issue by RoarGronmo** [simolus3/drift#1777]
**Is your feature request related to a problem? Please describe.**
When adding tables to the drift database, where I don't need preserve the database, it would have been very convenient to have a "fallback to destructive mode", more in the same way as the Room approach in android / java platform.

At the moment I have problems when publishing the web app to my test-group that added tables are not created.

**Describe the solution you'd like**
Please add some way to either 
1. simple function to reset database 
2. a mode when creating the database, which tells the db to be recreate when db schema version rises.

**Comment by simolus3** [comment]
Across all platforms, you can use

```dart
  @override
  MigrationStrategy get migration => destructiveFallback;
```

to manually delete and re-create all tables on a schema upgrade. This should also work on the web, let me know if you're running into any issues with that and I'll take a deeper look.

**Comment by RoarGronmo** [comment]
Thanx for answering, I'll check it out tomorrow morning !!
