### ISSUE TITLE
Fix documentation about clientDefault method

### ISSUE THREAD

**Issue by Alienjob** [simolus3/drift#1778]
https://drift.simonbinder.eu/api/drift/buildcolumn/clientdefault says
```
@override
  Set<Column> get primaryKey = {id};
```
when i run build_runner build, i see error:
```
This must return a set literal using the => syntax!
13 │   Set<Column> get primaryKey = {key};
```
Right way is using  `=>` instead `=`, like that:
```
 Set<Column> get primaryKey => {key};
```
please, fix the documentation

**Comment by simolus3** [comment]
Good catch, thanks! I've fixed this in a1c2ff893c93ba6efa38efdfb7a25c98857b213f.
