### ISSUE TITLE
Add `ignore all lints` comment to generated code

### ISSUE THREAD

**Issue by Pante** [simolus3/drift#1780]
It will be really nice if a `ignore_for_file: type=lint` comment is included in generated code. It ensures that dart analyzer will ignore the generated file without having to explicitly exclude it in a project's analysis_options.yaml.

**Comment by simolus3** [comment]
Wow, I didn't know about this selector but it seems super useful. Using it from 8e3259c971855cc10673b3c948240497e2a8de9a onwards.
