### ISSUE TITLE
Exception following discussion #1782

### ISSUE THREAD

**Issue by vicenterusso** [simolus3/drift#1783]
Discussion #[1782](https://github.com/simolus3/drift/discussions/1782)

Created isolate just like the docs. Then I tried to register with Getit

```dart
DatabaseConnection connection = _createDriftIsolateAndConnect();
final db = Database.connect(connection);
GetIt.instance.registerSingleton<Database>(db);
```
Later in `Sync` class I do:

```dart
db = GetIt.instance.get<Database>();
```
And I get the following error:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Instance of 'DriftRemoteException'
```
I removed the `Database() : super(_openConnection())` from Database class. I don't know exactly what to do know

Edit:

My Database class:

```dart
@DriftDatabase(
  include: {'tables.drift'},
)
class Database extends _$Database {
  // this is the new constructor
  Database.connect(DatabaseConnection connection) : super.connect(connection);
}
```

**Comment by simolus3** [comment]
This error means that there's something going wrong on the remote isolate, possible in your code opening the database. Unfortunately in the version on pub the `toString()` message doesn't point to the actual source. Could you add this to your pubspec and see where the error comes from?

```yaml
dependency_overrides:
  drift:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift
```

You could also catch the `DriftRemoteException` manually and print the `remoteCause` and the `remoteStackTrace` from the remote isolate.

**Comment by simolus3** [comment]
Closing this, if you have more details on the error and it turns out to be something in drift please let me know. I'll re-open and fix it then :)
