### ISSUE TITLE
Export wasm.dart (WasmDatabase)

### ISSUE THREAD

**Issue by zs-dima** [simolus3/drift#1789]
You created example with 'import 'package:drift/wasm.dart';'
but forgot to export WasmDatabase

https://github.com/simolus3/drift/blob/develop/examples/app/lib/database/connection/web.dart

Please, add missing export.

![image](https://user-images.githubusercontent.com/25195453/161589799-a3dde64c-44f3-4080-8a96-c58b9ae8ed8b.png)

Thanks in advance

**Comment by simolus3** [comment]
Thanks for checking the new example out! The state on the `develop` branch matches the current state of drift development, not all of that has been published to pub yet. There are known problems in that implementation that I have to fix first.

The next drift release will experimentally provide the `package:drift/wasm.dart` library. If you want to try it out before then, you'll have to use the [dependency overrides to git](https://drift.simonbinder.eu/docs/internals/#using-an-unreleased-drift-version). But really, I recommend using the other [web implementation](https://drift.simonbinder.eu/web/) for now.
