### ISSUE TITLE
Hope to provide documents in other languages.

### ISSUE THREAD

**Issue by ddxl123** [simolus3/drift#1792]
Such as Chinese, thank you very much!

**Comment by simolus3** [comment]
I can do the general work necessary to provide a language selection on the website, but most of the translations would have to come from the community. Keeping translated documentation up-to-date is really time-consuming, so it probably only makes sense for the most relevant part of the documentation (the getting started page + best practices around using drift).

**Comment by dickermoshe** [comment]
I'm going to close this as not planned.
Docs in multiple languages will only be possible if we have committed maintainers from multiple backgrounds.
We've only got "The Queen's English" and "Freedom English" at this point, so I'm going to close this as not planned.
