### ISSUE TITLE
Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN)

### ISSUE THREAD

**Issue by KhromovAlex** [simolus3/drift#1793]
I am getting this error

```
F/libc    (30958): Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x7c00008041 in tid 30986 (1.ui), pid 30958 (appName)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone64_arm64/emulator64_arm64:10/QSR1.210802.001/7603624:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-04-06 12:52:52+0700
pid: 30958, tid: 30986, name: 1.ui  >>> bundleId <<<
uid: 10311
signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x7c00008041
    x0  0000007c09f80079  x1  0000007c244cec21  x2  0000007c244cebc1  x3  0000007c00008071
    x4  0000007c244ceba1  x5  0000007c244ceb81  x6  0000007c244ceb61  x7  0000007c244ceb41
    x8  0000007c244ceb21  x9  0000007c244e7e81  x10 0000007c09f80129  x11 0000007c09f80079
    x12 0000007c244e7e41  x13 0000007c244e7e11  x14 0000007c244e7df1  x15 0000007d2b979238
    x16 0000000000000004  x17 0000000000000004  x18 0000007d2aee2000  x19 0000007c244e7dd1
    x20 0000007c244e7d91  x21 0000007d0fbdc2b8  x22 0000007c00008041  x23 0000007c244e7d61
    x24 0000007c244e7d31  x25 0000007c1cee7431  x26 0000007d8db19800  x27 0000007c0d6dd840
    x28 000000040000007c  x29 0000007d2b979350
    sp  0000007d2b8a1000  lr  0000007d400cf1b0  pc  0000007c00008041
backtrace: #00 pc 0000000000008041  <anonymous:7c00000000>
```

When the application starts in the repository, watchAll from the database is launched. When there are up to 1000 observable objects everything works well. After exceeding 2000-2500, the application crashes, with watchAll, or with simultaneous operation of updateAll and watchAll.

**Comment by simolus3** [comment]
Can you post more details or a small project to reproduce this? Are those 2000-2500 streams all backed by different SQL queries? Drift should merge queries if they're the same.

**Comment by KhromovAlex** [comment]
I am getting data from a server. When the number is greater than 2500 mainOperation an error occurs.
This is an example of dao:

`class MainOperationDao extends DatabaseAccessor<AppDatabase>
    with _$MainOperationDaoMixin {
  MainOperationDao(AppDatabase attachedDatabase)
      : super(attachedDatabase);

  Stream<List<MainOperationExpand>> watchAll() {
    final tableAliases = _createTableAliases();

    return select(mainOperations)
        .join(_getJoins(tableAliases))
        .watch()
        .map((list) {
      return list
          .fold(
            <String, MainOperationExpand>{},
            (
              Map<String, MainOperationExpand> previousValue,
              TypedResult row,
            ) =>
                _foldToMap(previousValue, row, tableAliases),
          )
          .values
          .toList();
    });
  }
_TableAliases _createTableAliases() => _TableAliases(
        mainCrop: alias(crops, _mainCropName),
        predecessor: alias(crops, _predecessorName),
      );

  List<Join> _getJoins(_TableAliases tableAliases) => [
        leftOuterJoin(
          statuses,
          statuses.id.equalsExp(mainOperations.statusID),
        ),
        leftOuterJoin(
          components,
          components.mainOperationID.equalsExp(mainOperations.id),
        ),
        leftOuterJoin(
          materials,
          materials.id.equalsExp(components.materialID),
        ),
        leftOuterJoin(
          fieldOnes,
          fieldOnes.id.equalsExp(mainOperations.fieldOneID),
        ),
        leftOuterJoin(
          fields,
          fields.id.equalsExp(mainOperations.fieldID),
        ),
        leftOuterJoin(
          operations,
          operations.id.equalsExp(mainOperations.operationID),
        ),
        leftOuterJoin(
          tableAliases.mainCrop,
          tableAliases.mainCrop.id.equalsExp(mainOperations.cropID),
        ),
        leftOuterJoin(
          tableAliases.predecessor,
          fieldOnes.id.equalsExp(mainOperations.predecessorID),
        ),
      ];

Future<void> updateList(List<MainOperation> list) async {
    await batch((batch) {
      batch.insertAllOnConflictUpdate(mainOperations, list);
    });
  }

Map<String, MainOperationExpand> _foldToMap(
    Map<String, MainOperationExpand> previousValue,
    TypedResult row,
    _TableAliases tableAliases,
  ) {
    final MainOperation? mainOperation = row.readTableOrNull(mainOperations);
    final db.Component? component = row.readTableOrNull(components);
    final Material? material = row.readTableOrNull(materials);
    final FieldOne? fieldOne = row.readTableOrNull(fieldOnes);
    final Status? status = row.readTableOrNull(statuses);
    final Field? field = row.readTableOrNull(fields);
    final Operation? operation = row.readTableOrNull(operations);
    final Crop? crop = row.readTableOrNull(tableAliases.mainCrop);
    final Crop? predecessor = row.readTableOrNull(tableAliases.predecessor);

    if (mainOperation != null) {
      previousValue.update(
        mainOperation.id,
        (old) {
          return old.copyWith(
            components: {
              ...old.components,
              if (component != null)
                ComponentExpand(
                  id: component.id,
                  mainOperationID: component.mainOperationID,
                  materialID: component.materialID,
                  material: material,
                ),
            }.toList(),
          );
        },
        ifAbsent: () {
          return MainOperationExpand(
            id: mainOperation.id,
            status: status,
            field: field,
            operation: operation,
            crop: crop,
            predecessor: predecessor,
            fieldOne: fieldOne,
            components: [
              if (component != null)
                ComponentExpand(
                  id: component.id,
                  mainOperationID: component.mainOperationID,
                  materialID: component.materialID,
                  material: material,
                ),
            ],
          );
        },
      );
    }

    return previousValue;
  }
}
`
