### ISSUE TITLE
Codegen issue in the example

### ISSUE THREAD

**Issue by zs-dima** [simolus3/drift#1796]
Drift example leads to `pub finished with exit code 78` error.
Looks `build.yaml` has issue:
https://github.com/simolus3/drift/blob/develop/examples/app/build.yaml

**Comment by simolus3** [comment]
Could you post the error message that you're getting? I can run `flutter pub run builld_runner build` just fine, also from a clean state.

**Comment by zs-dima** [comment]
@simolus3 sorry, I missed \tool\ folder, thanks a lot for your help.
