### ISSUE TITLE
Web example does not work

### ISSUE THREAD

**Issue by zs-dima** [simolus3/drift#1797]
Flutter Web drift example does not work.
Could be nice to create working example.

https://github.com/simolus3/drift/tree/develop/examples/app

![image](https://user-images.githubusercontent.com/25195453/162489443-16650c76-4748-436f-84de-78d71a955842.png)

**Comment by simolus3** [comment]
Thanks for the report, I've fixed this in https://github.com/simolus3/sqlite3.dart/commit/03c20dea603076913b0ed16d969d59b1082d1d7a.

> Could be nice to create working example.

Again, the `app` example is in development. There are multiple examples like [this one](https://github.com/simolus3/drift/tree/develop/examples/flutter_web_worker_example) or [this one](https://github.com/rodydavis/moor_shared) that work on the web right now.

**Comment by zs-dima** [comment]
@simolus3 thanks a lot for details, looks this '[flutter_web_worker_example](https://github.com/simolus3/drift/tree/develop/examples/flutter_web_worker_example)' example still has issue:
https://github.com/simolus3/drift/issues/1801
