### ISSUE TITLE
Using moor in desktop (windows) MissingPluginException

### ISSUE THREAD

**Issue by DjarallahBrahim** [simolus3/drift#1798]
Hello, 

in the documentation you mentionned that moor support desktop!

when i run my application i have this exception:

`flutter: widget.isNetworkImage false
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)`

pubspec:

`  moor_flutter: ^4.1.0
dev_dependencies:
  moor_generator: ^4.6.0+1
  build_runner: 2.1.8`

AppDataBAse:

`// This annotation tells the code generator which tables this DB works with
@UseMoor(tables: [PatientsTable])
// _$AppDatabase is the name of the generated class
class AppDatabase extends _$AppDatabase {
  AppDatabase()
      // Specify the location of the database file
      : super((FlutterQueryExecutor.inDatabaseFolder(
          path: 'db.sqlite',
          // Good for debugging - prints SQL in the console
          logStatements: true,
        )));

  // Bump this when changing tables and columns.
  // Migrations will be covered in the next part.
  @override
  int get schemaVersion => 1;

Expression<int> amountOfPatientsTable() => patientsTable.id.count();
  // All tables have getters in the generated class - we can select the tasks table
  Future<List<PatientsTableData>> getAllPatients() =>
      select(patientsTable).get();
  // Future<Patient> entryById(id) => select(patients).getSingle()..where;

  Future<PatientsTableData> getPatientById(int id) =>
      (select(patientsTable)..where((t) => t.id.equals(id))).getSingle();

  // Updates a Patient with a matching primary key
  Future updatePatient(PatientsTableData patient) =>
      update(patientsTable).replace(patient);

  Future<List<PatientsTableData>> getPatientsHistorique(int limit) {
    return (select(patientsTable)..limit(limit)).get();
  }

  Future insertPatient(PatientsTableData patient) =>
      into(patientsTable).insert(patient);
  Future insertPatientCompanions(PatientsTableCompanion patient) =>
      into(patientsTable).insert(patient);
}`

Ps: i already did flutter clean/update....

Any help please ?

**Comment by simolus3** [comment]
`sqflite`, which `moor_flutter` is based on, only works on Android and iOS. You can either depend on [sqflite_common_ffi](https://pub.dev/packages/sqflite_common_ffi) to get it working on Windows (but additional setup is likely needed for that too - see its readme.

For full cross-platform support, you could also use `package:moor/ffi.dart` (or `package:drift/native.dart`) instead of `moor_flutter`. An example for a cross-platform moor app is here: https://github.com/rodydavis/moor_shared.
