### ISSUE TITLE
Drift

### ISSUE THREAD

**Issue by stealingmyinfo** [simolus3/drift#1803]
I install the package and suddenly the Column widgets is no longer a recognized widget.

WTF?

**Comment by kuhnroyal** [comment]
WTF?

**Comment by kuhnroyal** [comment]
Drift has a `Column` class and when you import the drift package, you also import this class.
You can use 
`import 'package:drift/drift.dart' hide Column;`
or
`import 'package:drift/drift.dart' as drift;`

https://dart.dev/guides/language/language-tour#libraries-and-visibility

**Comment by simolus3** [comment]
Yup, what @kuhnroyal said. The drift package also exports a class named `Column`. Database tables have columns, so this is a fair class for drift to have and export and the workaround should do the trick. You only need it for files where you import both drift and Flutter and where you use a `Column`/`Table` widget, so hopefully not too often.
