### ISSUE TITLE
 dateTime().withDefault(Constant(DateTime.now()))() is not working as expected

### ISSUE THREAD

**Issue by Vedsaga** [simolus3/drift#1807]
below code was expected to auto-fill the exact DateTime when a new row is inserted into that table right?
```dart
DateTimeColumn get createdAt => dateTime().withDefault(Constant(DateTime.now()))();
```

but, instead above code actually retreving  dateTime of db-instace when that was created first time...

`e.g`

I have created a table call `OrderTable` that have `orderId` , `itemId` and `createdAt ` as columns...

now, suppose I created first orderId at `15 April 2022 7:30 IST ` so, what should be date `createdAt ` value ? it should be `15 April 2022 7:30 IST` right ? _(after  using `DateFormat` of flutter...)_ so far so good...

now suppose I am inserting another order Id but next day which is `16 April 2022 7:30 IST `  so, now what should be value for column `createdAt`  for orderId 2?  It should be  `16 April 2022 7:30 IST` right? but no in the DB for all order Id same value which is `15 April 2022 7:30 IST` set as  by default....

it means all columns are having same dateTime  `value` for and that value is the time when that DB instance was created for the first time...

I am not sure, if this is how `.withDefault(Constant(DateTime.now()))` architectured to behave... if so, then no issue I will make surefrom next time that I always  pass DateTime when ever new order is inserted...

**Comment by simolus3** [comment]
While I understand how this is a bit confusing, it's also working as intended: `withDefault` is evaluated once at the time the table is created (the constant is written into the `CREATE TABLE` statement). So as you observed, you are getting only the time from when the DB was created.

Luckily, sqlite3 supports the `CURRENT TIMESTAMP` expression that always evaluates to the current time. This one can be used in tables too, so you can fix your table definition with `.withDefault(currentDateAndTime)` (you'll have to either write a migration or delete the database during development for the table to be re-created).

If you want something that is evaluated for each insert, use [`clientDefault`](https://drift.simonbinder.eu/api/drift/buildcolumn/clientdefault) in the column builder (`.clientDefault(DateTime.now)`). But to get the current time, the builtin `currentDateAndTime` is preferable.

**Comment by Vedsaga** [comment]
Thank you @simolus3 again for quick response  :)
