### ISSUE TITLE
Object to companion convertion function

### ISSUE THREAD

**Issue by egyleader** [simolus3/drift#1808]
sometimes I need to convert class to it's companion with all the filled fields set to it's value and all null fields set to `Value.absent()`  without doing it manually .. 

example : convert a Message class to MessagesCompanion  with `message.toCompanion();`

could this be generated automatically for each table class ? or there is another way of doing that ?

**Comment by simolus3** [comment]
Yup! You can just enable the `data_class_to_companions` [build option](https://drift.simonbinder.eu/docs/advanced-features/builder_options/). Drift will then generate a `toCompanion(bool)` function, where the parameter controls whether null fields should be mapped to `Value.absent()` or to `Value(null)`.
