### ISSUE TITLE
Hope to add an interception mechanism for additions, deletions and changes (similar to triggers).

### ISSUE THREAD

**Issue by ddxl123** [simolus3/drift#1809]
There is an `ACompanion`, a `BCompanion`, and both have the same property `name`, I want to use a generic T to represent `ACompanion` and `BCompanion`, so that when calling the generic object, I can get the `name` property.
It seems that the `Companion` generated by Drift cannot be done unless an extension can be defined so that we can customize a `Companion` function. Is there such an extension?

For example, I want to achieve:
```
/// I have made mutable_classes: true so the Companion value can be modified.

void autoUpdateName(BaseCompanion base){
  /// There is actually a lot of processing logic in this function.
  base.name = 'newValue';
]

/// or like this:
/// void autoUpdateName<T extends BaseCompanion>(T base){
/// base.name = 'newValue';
/// }

/// Only age is modified here, and 'name' is not modified.
ACompanion a = ACompanion(age:Value(20));
BCompanion b = BCompanion(age:Value(30));

/// Use the autoUpdateName function uniformly to modify the name.
autoUpdateName(a);
autoUpdateName(b);

/// Perform the update.
await (update(table).replace(ACompanion()));
await (update(table).replace(BCompanion()));

```

Similar to triggers. But without using BaseCompanion or generics, I'd probably need to write a lot of triggers.

**Comment by simolus3** [comment]
This isn't great, but should probably work:

```dart
void autoUpdateName(Insertable base){
  /// There is actually a lot of processing logic in this function.
  (base as dynamic).name = 'newValue';
]
```

Maybe there could be support for custom companion classes or a custom class hierarchy in the future, but it will be non-trivial to implement and I don't really see the use outside of very special use-cases like yours. (I'm happy to change my opinion here if a common scenario that could benefit from this comes up).
