### ISSUE TITLE
Support toJson / fromJson in TypeConverter

### ISSUE THREAD

**Issue by North101** [simolus3/drift#1811]
Currently if you use a custom type and call DataClass.toJson / DataClass.fromJson it'll return the custom type and you need to override the default serializer to properly convert it. Instead, this could be handled by the TypeConverter for our custom type.

**Comment by simolus3** [comment]
I think this is a good idea, but I think we might not want to do this by default. There could be use-cases where the conversion from and to json has different types than the one to SQL (e.g. a column that's a custom object in Dart, a string in SQL and an int in json).

For the common cases where the types are the same, I've added the `JsonTypeConverter` mix-in. When it is mixed in into a type converter, drift will generate code to apply it for json serialization by default. This also preserves backwards compatibility :)
