### ISSUE TITLE
 schema dump fails when schema contains a VIEW

### ISSUE THREAD

**Issue by knaeckeKami** [simolus3/drift#1813]
Running `drift_dev schema dump` fails if the given schema contains a VIEW. The exception is:

``` 
Assertion failed: "unknown entity type Instance of 'MoorView'"
  #0      SchemaWriter._entityToJson (package:drift_dev/src/services/schema/schema_files.dart:68:7)
  #1      SchemaWriter.createSchemaJson (package:drift_dev/src/services/schema/schema_files.dart:32:43)
  #2      DumpSchemaCommand.run (package:drift_dev/src/cli/commands/schema/dump.dart:81:57)
  <asynchronous suspension>
  #3      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
  <asynchronous suspension>
  #4      MoorCli.run (package:drift_dev/src/cli/cli.dart:65:5)
  <asynchronous suspension>
  #5      run (package:drift_dev/src/cli/cli.dart:19:12)
  <asynchronous suspension>
```

Repro:

Create a dart project with this drift file:

db.drift:
```sql
CREATE VIEW IF NOT EXISTS repro AS
 SELECT 1 as col;
```

this db.dart file:

```dart
import 'package:drift/drift.dart';

part 'db.g.dart';

@DriftDatabase(
  include: {'db.drift'},
)
class Db  extends _$Db {

  @override
  int get schemaVersion => 1;

  Db.fromQueryExecutor(QueryExecutor queryExecutor) : super(queryExecutor);

}

```

and run `dart run drift_dev schema dump  lib/src/db.dart schema.json`

**Comment by simolus3** [comment]
Thanks for the report! This was mostly due to laziness on my part, but it turned out to be easier than I've thought in the end :D I've added support for views defined in `.drift` files in 80c8c86031e9adb194a2671f3752be6fff03c185. Dart-defined views are a lot harder to export statically, but I hope having support for those defined in `.drift` files already helps.

**Comment by knaeckeKami** [comment]
> Dart-defined views are a lot harder to export statically, but I hope having support for those defined in .drift files already helps.

Yes, since I use .drift files for pretty much everything it solves this for me ;)
