### ISSUE TITLE
Documentation issue: Advanced queries in Dart

### ISSUE THREAD

**Issue by ZhulanovAA** [simolus3/drift#1819]
In the "Group By" section, first example, it seems to be wrong table in the final output:

`print('there are ${row.read(amountOfTodos)} entries in ${row.readTable(todos)}');`

In the example we are trying to get amount of Todos in each Category but instead we are printing amount Todos in each Todo? Probably shoud be: 

`print('there are ${row.read(amountOfTodos)} entries in ${row.readTable(categories)}');`

If I understand correctly.

**Comment by simolus3** [comment]
Thanks for the report! I've updated the documentation in d23028a5bb9e8246005d08a6a8edbce3cd4b8a4b, it will go live soon.
