### ISSUE TITLE
TypeCast problem in Join query

### ISSUE THREAD

**Issue by pbayog00** [simolus3/drift#1824]
I am trying to run a join query between two tables and return a Stream of one of the tables, but I'm facing an error with very little information. I have tried debugging but the terminal shows no exception or error, it's just the message shown on the screen via a StreamBuilder in which I try to show the information.

I also tried the same query without the "where" code but I faced the same problem.

Any clues on that issue?

Thanks in advance!
![image](https://user-images.githubusercontent.com/47598318/165504903-02e78f1a-8b0c-486b-b044-ade6bca520c4.png)

**Comment by pbayog00** [comment]
I forgot to attach the error message, here it is.
![image](https://user-images.githubusercontent.com/47598318/165505079-d8db3187-4396-4aaf-acab-50a2d44be6c3.png)

**Comment by simolus3** [comment]
Is `Vendedor` a drift-generated class? If so, you can probably just do `return row?.readTable(vendedores)` in `_rowToObject`.

In addition to the error message, could you post the stack trace where exactly the error comes from (use `AsyncSnapshot.stackTrace` in the `StreamBuilder`)?

**Comment by pbayog00** [comment]
Yes, Vendedor is a drift-generated class and returning that worked for me, thank you for the refactor.

The problem seems to be that I needed to return if the query had no value, but I was trying to return Vendedor instead of Vendedor?. It is working now.

Also, the typecast error that I was facing was resolved with your refactor.

Thanks for your help!!
