### ISSUE TITLE
Documentation issue: DartTables indexing

### ISSUE THREAD

**Issue by FMorschel** [simolus3/drift#1827]
I would like to ask for a `DartTables` documentation index so that people could more easily find `Nullability`, `Primary keys`, `Views` and others.
I only found the Views explanation from the `View` class.

**Comment by simolus3** [comment]
I'm not sure what exactly you mean with a documentation index? Do you think https://drift.simonbinder.eu/docs/getting-started/advanced_dart_tables/ is not linked prominently enough?

**Comment by FMorschel** [comment]
I meant on the left side of the screen, where you have the pages indexes, you could add your topics at an even lower level like these links:
https://drift.simonbinder.eu/docs/getting-started/advanced_dart_tables/#names
https://drift.simonbinder.eu/docs/getting-started/advanced_dart_tables/#nullability
https://drift.simonbinder.eu/docs/getting-started/advanced_dart_tables/#default-values
and so on.

**Comment by simolus3** [comment]
The navigation bar on the left only shows pages, I think it would get very messy if every heading was shown there as well. There's a table of contents on the right though: 

![](https://user-images.githubusercontent.com/5738860/166122766-2844f98f-9514-49af-bcce-e9df5048cb72.png)

I'll change the headline of that page to also mention these features, that should hopefully make it clearer that they exist.
