### ISSUE TITLE
groupConcat distinct

### ISSUE THREAD

**Issue by DevHachi** [simolus3/drift#1833]
It would be nice if groupConcat could also have the attribute `distinct` the same way count have it.

Maybe something like this:
```
Expression<String?> groupConcat({String separator = ',', bool distinct}) {
    const sqliteDefaultSeparator = ',';
    if (separator == sqliteDefaultSeparator) {
      return _AggregateExpression('GROUP_CONCAT', this, distinct: distinct);
    } else {
      return FunctionCallExpression(
          'GROUP_CONCAT', [this, Variable.withString(separator)]);
    }
  }
```

**Comment by simolus3** [comment]
Good idea, I've added support for `distinct` and also `filter` in beee07608a992fd8a10cc1bd13f96a933d3bc712.

**Comment by Mike278** [comment]
Unfortunately sqlite doesn't support both `DISTINCT` and a custom separator. 

> In any aggregate function that takes a single argument, that argument can be preceded by the keyword DISTINCT

https://www.sqlite.org/lang_aggfunc.html

So it works for the single-argument version of `GROUP_CONCAT`, but there's parsing ambiguity using `DISTINCT` in the 2-argument version: does a comma indicate a list of expressions passed to `DISTINCT`, or does it indicate the beginning of a 2nd argument to `GROUP_CONCAT`? 

Source: I ran into this a few months ago for the first time 😛

**Comment by simolus3** [comment]
Thanks for pointing this out! Of course it ends up being the one combination I didn't write an integration test for, shame on me :D

I've added a check for this to `groupConcat` so that we now throw an `ArgumentError` directly. I've also added a lint catching this misuse in `sqlparser`.
