### ISSUE TITLE
Drift dev warning 

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/drift#1834]
Hello!
I was wondering if it would be possible to whitelist the expression `strftime('%s','now')` as a numeric number in the drift generator.
While operating with it in drift files a warning is raised saying that the expression should be numeric.
Example: `strftime('%s','now') * 1000`

Thank you!

**Comment by simolus3** [comment]
I think I'll just remove that lint. We could improve the type system to denote things like "string that's a formatted integer", but that just complicates things and IMO the lint doesn't provide enough value to justify the false-positives.

**Comment by simolus3** [comment]
Removed in 5e3de2fb7cf229ff2e725ad12e4cd909f1d0951b!
