### ISSUE TITLE
Following the documentation stuck on build_runner

### ISSUE THREAD

**Issue by blinnqipa** [simolus3/drift#1837]
Following the documentation at https://drift.simonbinder.eu/docs/getting-started / , but can not advance past declaring a table. Running build_runner results in `[SEVERE] Nothing can be built, yet a build was requested.` therefore not generating the .g.dart files at all. Tried pub clean, pub get and all, to no avail. Am I missing something?
Packages used:

```
  drift: ^1.6.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
```

` build_runner: ^2.1.10 `

Complete logs:

```
[INFO] Generating build script...
[INFO] Generating build script completed, took 422ms

[INFO] Precompiling build script......
[INFO] Precompiling build script... completed, took 4.4s

[SEVERE] Nothing can be built, yet a build was requested.
[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 453ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] Running build completed, took 3ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 37ms

[INFO] Succeeded after 56ms with 0 outputs (0 actions)
```

**Comment by simolus3** [comment]
Hi, could you please double-check that you have a dependency on `drift_dev` and that the `.dart` file declaring your table is in `lib/`?

**Comment by blinnqipa** [comment]
@simolus3 thank you, `drift_dev` fixed the issue for me. Now `.g.dart` file is created. Should I move the `.dart` file to `lib/`? If that is best practice?

**Comment by simolus3** [comment]
@blinnqipa Glad that solved your issue! Yes, a common practice is to have Dart files in `lib` (or some other folders like `test`). You can also see this when you run `flutter create` for instance, the `main.dart` file (and typically the rest of your application code) goes into the `lib/` folder next to your pubspec.

**Comment by blinnqipa** [comment]
Ah sorry misunderstood. Thought that I HAD to place that dart file in lib/ folder. Currently it is in a subfolder in lib/. Thank you again :).
