### ISSUE TITLE
Hope to provide Companion a constructor that requires every parameter.

### ISSUE THREAD

**Issue by ddxl123** [simolus3/drift#1852]
Hope to provide Companion a constructor that requires every parameter.

Whether the parameter is absent by setting it manually.
Every time I create a new Companion, I need to carefully check which value I may have forgotten to fill in.

**Comment by simolus3** [comment]
I don't really see how this could be useful given the existing options that exist for this:

- If you want to construct a full row with every parameter set (it looks like this is what you need), why not construct the corresponding data class instead? Its constructor requires every (non-nullable) value to be set. You can use `toCompanion` to convert a data class to a companion.
- If you want to be sure you're setting all required fields for inserts, use the `.insert` named constructor on the companion.

**Comment by ddxl123** [comment]
> I don't really see how this could be useful given the existing options that exist for this:
> 
> * If you want to construct a full row with every parameter set (it looks like this is what you need), why not construct the corresponding data class instead? Its constructor requires every (non-nullable) value to be set. You can use `toCompanion` to convert a data class to a companion.
> * If you want to be sure you're setting all required fields for inserts, use the `.insert` named constructor on the companion.

@simolus3 

Yes, I want to construct a whole row with each parameter, but some parameters are nullable.

If I use data class to construct row, the editor can easily generate required parameters (non-required parameter editors cannot be automatically generated).
This makes it easy to forget to assign values to some non-required parameters.

For example,
Write 'User' in the editor and press Enter, the required parameter is automatically generated:
```User(id: id, createdAt: createdAt, updatedAt: updatedAt)```
But the editor does not automatically generate `username` (non-required parameter), which makes it easy to forget the modification of `username`.

This feature is optional, but I think if it is provided, it can make my code more rigorous.
