### ISSUE TITLE
: error GD6C8354B: 'JsonKey' is imported from both 'package:drift/src/dsl/dsl.dart' and 'package:json_annotation/src/json_key.dart'.

### ISSUE THREAD

**Issue by Vedsaga** [simolus3/drift#1854]
**Describe the bug**

I am getting this error message when I do the `flutter run` command.

![image](https://user-images.githubusercontent.com/59083528/170027663-c837cdcc-3ebe-4932-8244-7634ff4bcb76.png)

```txt
[+10559 ms] [+10435 ms] lib/modules/login/bloc/login_bloc.freezed.dart(150,4): error GD6C8354B: 'JsonKey' is imported from both
'package:drift/src/dsl/dsl.dart' and 'package:json_annotation/src/json_key.dart'.
[C:\bitecope\salesman\build\windows\flutter\flutter_assemble.vcxproj]
```

I am using 
`  drift: ^1.6.0`
`  freezed_annotation: ^2.0.3`
`  json_annotation: ^4.5.0` as main dependency.

because I get this issue when I run the flutter command flutter run that means I am can't make any further progress till this issue is fixed :( 

any help would be highly appreciated. I have also raised this same issue in Freezed so, far got no help :(
https://github.com/rrousselGit/freezed/issues/488

**Comment by simolus3** [comment]
When you import drift into the file for which freezed generates, can you instead `import 'package:drift/drift.dart' hide JsonKey`? That should resolve this issue.

**Comment by Vedsaga** [comment]
```dart
import 'package:freezed_annotation/freezed_annotation.dart' hide JsonKey;
```

Thank you so much this solved the issue :)
