### ISSUE TITLE
 The `UNIXEPOCH` function is not available in SqliteVersion(3, 34, 0)

### ISSUE THREAD

**Issue by the4thfloor** [simolus3/drift#1857]
This is correct, [the `unixepoch()` function was added with version 3.38.0](https://www.sqlite.org/changes.html#version_3_38_0).

But I'm using `sqlite3` version 1.7.1 and `sqlite3_flutter_libs` version 0.5.7 which comes with sqlite3 version 3.38.5.
So the warning is wrong.

It is gone when I [manually override the SQLite version](https://drift.simonbinder.eu/options/#assumed-sql-environment) to "3.38".

**Comment by kuhnroyal** [comment]
The sqlite version can not be automatically determined for static analysis, that is why you have to manually set the version that you expect to be used.
Everything is working as intended here.

**Comment by simolus3** [comment]
Yup, working as intended. `drift_dev` can't know how exactly you're connecting to the database in the end, so there's a conservative assumption about available features. I've slightly changed the error message to point to the right section in 117fb19db4b4acb8040e9f1d713803c548d33794, but overall I think the current situation is reasonably handled in drift.
