### ISSUE TITLE
`app.sqlite` is not getting deleted

### ISSUE THREAD

**Issue by Vedsaga** [simolus3/drift#1865]
**Describe the bug**

So, when user click on logout then I am calling to delete for each table. 
```dart
  // delete all the tables
  Future<void> deleteEverything() {
    return transaction(() async {
      await customStatement('PRAGMA foreign_keys = OFF');
      for (final table in allTables) {
        // type arguments for generic method 'delete<T extends Table, D>
        // Try adding an explicit type,
        //for example: delete<UserTable, UserTableData>(table)
        await delete<Table, dynamic>(table).go();
      }
      await customStatement('PRAGMA foreign_keys = ON');
    });
  }
```

But, `app.sqlite` file still exist. 
![image](https://user-images.githubusercontent.com/59083528/170882487-a0aa04c5-49bf-4703-9889-fa7b3a60c94d.png)

So, is there any way possible to delete `app.sqlite` completely when user click on logout button...

**Comment by Vedsaga** [comment]
This happens for both `android `and `windows`.

**Comment by simolus3** [comment]
The reason that this doesn't delete the file is that deleting from a table will only remove the affected rows (in your case, all rows). But sqlite3 will keep the table schema in the database file, so it doesn't delete the entire database file.

> So, is there any way possible to delete `app.sqlite` completely when user click on logout button...

For that to work reliably, you'd have to:

1. Close your database (call and await `yourDatabase.close()`).
2. Delete the database file (using `File.delete`).
3. Possibly open the database again, upon which drift will automatically create all tables again.

But if your intention is to remove user data from that file, you can just keep running the delete statements and then issue a `customStatement('VACUUM')` in the end. That will keep the table structure in the database so you don't have to re-create the tables. I don't see a compelling reason to fully delete the file, it doesn't give you any security benefits.

**Comment by Vedsaga** [comment]
Really appreciate the quick response.  mm, so moving own-wards will not going to delete the files I will stick with what you advice.... (because it seems it required further permission to access file.)
