### ISSUE TITLE
CREATE TABLE at runtime 

### ISSUE THREAD

**Issue by hosseinkhojany** [simolus3/drift#1874]
I want my table to be created at runtime, not in compile time. For example, I have a table called a and another table I want to have with fields a called b that are separate. I want to do this for search speed.

**Comment by simolus3** [comment]
> INDEX is faster than VIEW ?

As far as I know, views don't bring a performance benefit. The definition of the view is essentially inlined into the `SELECT` query, so views are mostly used to make common queries easier to write.

Using an index on columns can speed up _some_ queries. E.g. if you're looking for something like `SELECT * FROM table WHERE a = 123`, having an index on `a` may make the query faster. But note that you don't need an index for foreign keys or primary keys, sqlite3 will create those for you.

**Comment by hosseinkhojany** [comment]
Dear Simon my favorite brother how are you ?

I got error ran the project with import 'package:sqlite3/wasm.dart';

I used sqlite3: ^1.7.0

MY FLUTTER DOCTER -------------------------
/home/khoujani/Documents/flutter/3.0.0/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.0.0, on Ubuntu 20.04.3 LTS 5.4.0-050400-generic, locale en_US.UTF-8)
• Flutter version 3.0.0 at /home/khoujani/Documents/flutter/3.0.0/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision ee4e09cce0 (4 weeks ago), 2022-05-09 16:45:18 -0700
• Engine revision d1b9a6938a
• Dart version 2.17.0
• DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
• Android SDK at /usr/lib/android-sdk
✗ cmdline-tools component is missing
Run path/to/sdkmanager --install "cmdline-tools;latest"
See https://developer.android.com/studio/command-line for more details.
✗ Android license status unknown.
Run flutter doctor --android-licenses to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
• Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
• clang version 10.0.0-4ubuntu1
• cmake version 3.16.3
• ninja version 1.10.0
• pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
• Android Studio at /home/khoujani/ANDROID/android-2021.1.1
• Flutter plugin version 64.0.2
• Dart plugin version 211.7798
• Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code
• VS Code at /snap/code/current
• Flutter extension version 3.40.0

[✓] Connected device (2 available)
• Linux (desktop) • linux • linux-x64 • Ubuntu 20.04.3 LTS 5.4.0-050400-generic
• Chrome (web) • chrome • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability
• All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0
ERROR ----------------------------------------------------------
/home/khoujani/Documents/flutter/3.0.0/flutter/bin/cache/dart-sdk/bin/dart --enable-asserts /home/khoujani/ANDROID/projects/TelFlutter/Telegram_Flutter/lib/main2.dart
../../../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.1/lib/src/wasm/file_system.dart:3:8: Error: Not found: 'dart:html'
import 'dart:html';
^
../../../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.1/lib/src/wasm/js_interop.dart:2:8: Error: Not found: 'dart:html'
import 'dart:html';
^
../../../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.4/lib/js_util.dart:8:1: Error: Not found: 'dart:js_util'
export 'dart:js_util';
^
../../../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.1/lib/src/wasm/file_system.dart:217:3: Error: Type 'Database' not found.
Database? _database;
^^^^^^^^
../../../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.1/lib/src/wasm/file_system.dart:224:3: Error: Type 'KeyRange' not found.
KeyRange _rangeOverFile(int fileId,
^^^^^^^^
../../../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.1/lib/src/wasm/file_system.dart:304:32: Error: Type 'Transaction' not found.
Future<_FileEntry> _readFile(Transaction transaction, int fileId) {
^^^^^^^^^^^
../../../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.1/lib/src/wasm/js_interop.dart:34:10: Error: Type 'KeyRange' not found.
external KeyRange keyRangeOnly(dynamic vaue);
^^^^^^^^
../../../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.1/lib/src/wasm/js_interop.dart:37:10: Error: Type 'KeyRange' not found.
external KeyRange keyRangeBound(dynamic lower, dynamic higher);
^^^^^^^^
../../../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.1/lib/src/wasm/js_interop.dart:39:29: Error: Type 'ObjectStore' not found.
extension ObjectStoreExt on ObjectStore {
^^^^^^^^^^^
../../../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.1/lib/src/wasm/js_interop.dart:41:12: Error: Type 'Request' not found.
external Request _put_1(dynamic value, dynamic key);
^^^^^^^

Process finished with exit code 254
