### ISSUE TITLE
I got error when ran the project with import 'package:sqlite3/wasm.dart';

### ISSUE THREAD

**Issue by hosseinkhojany** [simolus3/drift#1879]
I used sqlite3: ^1.7.0

MY FLUTTER DOCTER -------------------------
/home/khoujani/Documents/flutter/3.0.0/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.0.0, on Ubuntu 20.04.3 LTS 5.4.0-050400-generic, locale en_US.UTF-8)
• Flutter version 3.0.0 at /home/khoujani/Documents/flutter/3.0.0/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision ee4e09cce0 (4 weeks ago), 2022-05-09 16:45:18 -0700
• Engine revision d1b9a6938a
• Dart version 2.17.0
• DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
• Android SDK at /usr/lib/android-sdk
✗ cmdline-tools component is missing
Run path/to/sdkmanager --install "cmdline-tools;latest"
See https://developer.android.com/studio/command-line for more details.
✗ Android license status unknown.
Run flutter doctor --android-licenses to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
• Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
• clang version 10.0.0-4ubuntu1
• cmake version 3.16.3
• ninja version 1.10.0
• pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
• Android Studio at /home/khoujani/ANDROID/android-2021.1.1
• Flutter plugin version 64.0.2
• Dart plugin version 211.7798
• Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code
• VS Code at /snap/code/current
• Flutter extension version 3.40.0

[✓] Connected device (2 available)
• Linux (desktop) • linux • linux-x64 • Ubuntu 20.04.3 LTS 5.4.0-050400-generic
• Chrome (web) • chrome • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability
• All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0

ERROR ----------------------------------------------------------

../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/file_system.dart:217:3: Error: Type 'Database' not found.
  Database? _database;
  ^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/file_system.dart:224:3: Error: Type 'KeyRange' not found.
  KeyRange _rangeOverFile(int fileId,
  ^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/file_system.dart:304:32: Error: Type 'Transaction' not found.
  Future<_FileEntry> _readFile(Transaction transaction, int fileId) {
                               ^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:34:10: Error: Type 'KeyRange' not found.
external KeyRange keyRangeOnly(dynamic vaue);
         ^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:37:10: Error: Type 'KeyRange' not found.
external KeyRange keyRangeBound(dynamic lower, dynamic higher);
         ^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:39:29: Error: Type 'ObjectStore' not found.
extension ObjectStoreExt on ObjectStore {
                            ^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:41:12: Error: Type 'Request' not found.
  external Request _put_1(dynamic value, dynamic key);
           ^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:44:12: Error: Type 'Request' not found.
  external Request _put_2(dynamic value);
           ^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:47:12: Error: Type 'Request' not found.
  external Request getValue(dynamic key);
           ^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:53:3: Error: Type 'Request' not found.
  Request putRequestUnsafe(dynamic value, [dynamic key]) {
  ^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:61:12: Error: Type 'Request' not found.
  external Request openCursorNative(Object? range);
           ^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:64:12: Error: Type 'Request' not found.
  external Request openCursorNative2(Object? range, String direction);
           ^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:67:23: Error: Type 'Index' not found.
extension IndexExt on Index {
                      ^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:69:12: Error: Type 'Request' not found.
  external Request openKeyCursorNative();
           ^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:72:25: Error: Type 'Request' not found.
extension RequestExt on Request {
                        ^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:86:46: Error: Type 'Cursor' not found.
  StreamIterator<T> cursorIterator<T extends Cursor>() {
                                             ^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:125:31: Error: Type 'Cursor' not found.
class _CursorReader<T extends Cursor> implements StreamIterator<T> {
                              ^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:129:9: Error: Type 'Request' not found.
  final Request _cursorRequest;
        ^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:169:12: Error: Type 'IdbFactory' not found.
  external IdbFactory? get indexedDB;
           ^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:172:28: Error: Type 'IdbFactory' not found.
extension IdbFactoryExt on IdbFactory {
                           ^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:48:14: Error: Method not found: 'allowInterop'.
    getPath: allowInterop(strategy.getPath),
             ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:49:15: Error: Method not found: 'allowInterop'.
    getState: allowInterop(strategy.getState),
              ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:50:26: Error: Method not found: 'allowInterop'.
    addPopStateListener: allowInterop(strategy.addPopStateListener),
                         ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:51:25: Error: Method not found: 'allowInterop'.
    prepareExternalUrl: allowInterop(strategy.prepareExternalUrl),
                        ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:52:16: Error: Method not found: 'allowInterop'.
    pushState: allowInterop(strategy.pushState),
               ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:53:19: Error: Method not found: 'allowInterop'.
    replaceState: allowInterop(strategy.replaceState),
                  ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:54:9: Error: Method not found: 'allowInterop'.
    go: allowInterop(strategy.go),
        ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/responsive_framework-0.1.9/lib/responsive_wrapper.dart:622:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/flutter/3.0.0/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/responsive_framework-0.1.9/lib/responsive_wrapper.dart:623:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/flutter/3.0.0/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/responsive_framework-0.1.9/lib/responsive_wrapper.dart:635:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/flutter/3.0.0/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/responsive_framework-0.1.9/lib/responsive_wrapper.dart:645:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/flutter/3.0.0/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/file_system.dart:217:3: Error: 'Database' isn't a type.
  Database? _database;
  ^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/file_system.dart:235:33: Error: 'Database' isn't a type.
    final completer = Completer<Database>.sync();
                                ^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/file_system.dart:240:50: Error: 'Database' isn't a type.
        final database = change.target.result as Database;
                                                 ^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/file_system.dart:304:32: Error: 'Transaction' isn't a type.
  Future<_FileEntry> _readFile(Transaction transaction, int fileId) {
                               ^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/file_system.dart:332:25: Error: 'CursorWithValue' isn't a type.
        .cursorIterator<CursorWithValue>();
                        ^^^^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/file_system.dart:363:55: Error: 'CursorWithValue' isn't a type.
        blocks.openCursorNative(range).cursorIterator<CursorWithValue>();
                                                      ^^^^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/file_system.dart:430:26: Error: 'CursorWithValue' isn't a type.
          .completed<idb.CursorWithValue?>();
                         ^^^^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:129:9: Error: 'Request' isn't a type.
  final Request _cursorRequest;
        ^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:444:19: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        'random': allowInterop((Pointer ptr, int length) {
                  ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:452:22: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        'error_log': allowInterop((Pointer ptr) {
                     ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:455:16: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        'now': allowInterop(() {
               ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:459:13: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
            allowInterop((Pointer source, Pointer dest, int length) {
            ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:470:27: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        'function_xFunc': allowInterop((Pointer ctx, int args, Pointer value) {
                          ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:473:27: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        'function_xStep': allowInterop((Pointer ctx, int args, Pointer value) {
                          ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:477:13: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
            allowInterop((Pointer ctx, int args, Pointer value) {
            ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:480:28: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        'function_xFinal': allowInterop((Pointer ctx) {
                           ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:483:28: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        'function_xValue': allowInterop((Pointer ctx) {
                           ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:486:28: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        'function_forget': allowInterop((Pointer ctx) => functions.forget(ctx)),
                           ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:487:26: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        'function_hook': allowInterop(
                         ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:506:22: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        'fs_create': allowInterop((Pointer path, int flags) {
                     ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:523:27: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        'fs_temp_create': allowInterop(() {
                          ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:527:20: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        'fs_size': allowInterop((Pointer path, Pointer pSize) {
                   ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:540:24: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        'fs_truncate': allowInterop((Pointer path, int size) {
                       ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:548:20: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        'fs_read': allowInterop(
                   ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:559:21: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        'fs_write': allowInterop(
                    ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:571:22: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        'fs_delete': allowInterop((Pointer path) {
                     ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart:579:22: Error: The method 'allowInterop' isn't defined for the class '_InjectedValues'.
 - '_InjectedValues' is from 'package:sqlite3/src/wasm/bindings.dart' ('../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/bindings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        'fs_access': allowInterop((Pointer path, int flags, Pointer pResOut) {
                     ^^^^^^^^^^^^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:41:20: Error: JS interop or Native class required for 'external' extension members.
Try adding a JS interop annotation to the on type class of the extension.
  external Request _put_1(dynamic value, dynamic key);
                   ^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:44:20: Error: JS interop or Native class required for 'external' extension members.
Try adding a JS interop annotation to the on type class of the extension.
  external Request _put_2(dynamic value);
                   ^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:47:20: Error: JS interop or Native class required for 'external' extension members.
Try adding a JS interop annotation to the on type class of the extension.
  external Request getValue(dynamic key);
                   ^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:61:20: Error: JS interop or Native class required for 'external' extension members.
Try adding a JS interop annotation to the on type class of the extension.
  external Request openCursorNative(Object? range);
                   ^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:64:20: Error: JS interop or Native class required for 'external' extension members.
Try adding a JS interop annotation to the on type class of the extension.
  external Request openCursorNative2(Object? range, String direction);
                   ^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:69:20: Error: JS interop or Native class required for 'external' extension members.
Try adding a JS interop annotation to the on type class of the extension.
  external Request openKeyCursorNative();
                   ^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:74:24: Error: JS interop or Native class required for 'external' extension members.
Try adding a JS interop annotation to the on type class of the extension.
  external dynamic get _rawResult;
                       ^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.7.0/lib/src/wasm/js_interop.dart:174:19: Error: JS interop or Native class required for 'external' extension members.
Try adding a JS interop annotation to the on type class of the extension.
  external Object _jsDatabases();
                  ^
Failed to compile application.

**Comment by simolus3** [comment]
I've answered in https://github.com/simolus3/sqlite3.dart/issues/104, let's keep the discussion there if you have more questions on this.

By the way: There is no reason to ask the same question three times! I get notifications for each of them and I'll reply to them when I have time. You can ping me again after a couple of days if I missed something, but posting this across boards won't make me reply faster.
