### ISSUE TITLE
[BUG] android_metadata table is not ignored when using validateDatabaseSchema

### ISSUE THREAD

**Issue by lucasdidur** [simolus3/drift#1885]
When I use validateDatabaseSchema(), I get error because the android_metadata table

```
E/flutter (28772): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Schema does not match
E/flutter (28772): additional:
E/flutter (28772):  Contains the following unexpected entries: android_metadata
E/flutter (28772):
E/flutter (28772): #0      verify
package:drift_dev/…/schema/verifier_impl.dart:132
E/flutter (28772): #1      VerifySelf.validateDatabaseSchema
package:drift_dev/api/migrations.dart:96
E/flutter (28772): <asynchronous suspension>
```

**Comment by Mike278** [comment]
I've run into this with some of our tools too - there's also `sqlite_sequence` where auto-increment metadata is stored, and `sqlite_stat1`/`sqlite_stat4` (depending on sqlite version) where the `ANALYZE` command writes query planner metadata.

**Comment by simolus3** [comment]
Are you aware of a list for those internal tables? We're ignoring `sqlite_autoindex*` and any table that starts with `$v_` if there's a virtual table named `v`. I'm wondering if it's safe to just ignore to all tables starting with `sqlite_`, I guess it is?

**Comment by Mike278** [comment]
Yeah looks like `sqlite_%` is the right heuristic: 

> The names of internal schema objects always begin with "sqlite_" and any table, index, view, or trigger whose name begins with "sqlite_" is an internal schema object. SQLite prohibits applications from creating objects whose names begin with "sqlite_".

https://www.sqlite.org/fileformat2.html#storage_of_the_sql_database_schema

**Comment by simolus3** [comment]
Nice find! I've adapted this in 7be4e90569cd5647cfbfe689688c05c677ffd4cb.
