### ISSUE TITLE
Ability to do an insert without re-running query streams

### ISSUE THREAD

**Issue by cal-g** [simolus3/drift#1886]
**Is your feature request related to a problem? Please describe.**

I am listening to changes on a table using `watch` and also have a background download process (in separate isolate) running at the same time which inserts many records ( > 1000 records) using the `into(table_name).insert(record)` statement for each record and this causes the `watch` to emit an event for each insert.  
I am also using the https://pub.dev/packages/diffutil_dart package to check for changes (create, update, etc.) in the List of data emitted for each `watch` event and this would result in a lot of processing on the main thread. Due to this heavy processing on the main thread the UI is adversely affected. I could use a `customInsert` without setting the `updates` parameter but is it possible to still use the `into(table_name).insert(record)` but not re-run the stream query ?

**Describe the solution you'd like**

Perhaps the `insert` could have another named optional parameter of type bool, say `updateStreamQuery`  and passing `false` would not re-run the stream query.
e.g. `into(table_name).insert(record , updateStreamQuery : false)`

**Comment by North101** [comment]
Are you running the inserts in a transaction? This will only cause the watch to emit once the transaction is complete

```dart
db.transaction(() async {
    ...
});
```

You could also use batches which are more efficient at inserting/updating/deleting multiple items from the same table
```dart
  await batch((batch) {
    // functions in a batch don't have to be awaited - just
    // await the whole batch afterwards.
    batch.insertAll(todos, [
      TodosCompanion.insert(
        title: 'First entry',
        content: 'My content',
      ),
      TodosCompanion.insert(
        title: 'Another entry',
        content: 'More content',
        // columns that aren't required for inserts are still wrapped in a Value:
        category: Value(3),
      ),
      // ...
    ]);
  });
```

**Comment by cal-g** [comment]
No I'm not running it in a transaction or using a batch. I could use a batch to make the inserts efficient but that would still cause the `watch` stream query to re-run once. 
I'm looking for a solution where I can do the downloads (insert) using the `into(table).insert(record)` query but at the same time this query shall not notify the stream query of the table changes

**Comment by simolus3** [comment]
> I could use a batch to make the inserts efficient but that would still cause the `watch` stream query to re-run once.

Once for the entire transaction or batch though, which is much better than once for each row! Streams created outside of a transaction will only be updated once after the transaction completes (the same goes for batches, which use transactions internally).

>  I'm looking for a solution where I can do the downloads (insert) using the `into(table).insert(record)` query but at the same time this query shall not notify the stream query of the table changes

I think this is very rarely needed and shouldn't be part of drift. Instead of relying of some built-in mechanism, you could also do something like this:

- Call `StreamSubscription.pause` on the listener you want to pause while downloads are being processed.
- Run the code inserting all the downloads.
- Call `SttreamSubscription.resume`.

But since it's probably ok to get notified once, I'd just use transactions.
