### ISSUE TITLE
Documentation issue: Expressions

### ISSUE THREAD

**Issue by mkhan-akhan** [simolus3/drift#1892]
Exists
Regarding the example code:

Future<List<Category>> emptyCategories() {
  final hasNoTodo = notExistsQuery(
      select(todos)..where((row) => row.category.equalsExp(categories.id)));
  return select(categories)..where((row) => hasNoTodo);
}

Visual Studio Code indicates problems with the return statement. The problems are resolved when the return statement is changed to:

return (select(categories)..where((row) => hasNoTodo)).get();

**Comment by simolus3** [comment]
Thanks for the report! I've fixed this in 4af9aed1905d618475a63e4a18a464bde7f35a91.
