### ISSUE TITLE
notExistsQuery Where function not fully referencing 'other' table column in Select statement with no Joins

### ISSUE THREAD

**Issue by mkhan-akhan** [simolus3/drift#1894]
The notExistsQuery Function based on the sample code provided in the documentation under header Expressions, sub-header Exists, is not returning the expected number of empty categories.

I added an emptyCategories function, based on the sample code in the documentation, to the drift/examples/app drift 1.6.0:

```dart
  Future<List<Category>> emptyCategories() {
    final hasNoTodo = notExistsQuery(select(todoEntries)
      ..where((row) => row.category.equalsExp(categories.id)));
    return (select(categories)..where((row) => hasNoTodo)).get();
  }
```

I modified the home.dart void _addTodoEntry() function by inserting a call to the above function:

```dart
void _addTodoEntry() async {
....
var emptyCategories = await database.emptyCategories();
....
}
```

I also added a medium category and a low category without any todo entries, in the database class (database.dart). Thus, I expected the emptyCategories list to have 2 items only. Instead I saw all three categories.

The behaviour can be reproduced and observed by adding my changes above to the drift/examples/app, putting breakpoint at the emptyCategories variable in the home.dart page and adding a new task.

I observed the ctx.sql variable in the get() function of the SimpleSelectStatement class and noticed that the categories id column is not fully referenced. Presently the sql statement generated is as follows:

```sql
SELECT * FROM categories WHERE NOT EXISTS (SELECT * FROM todo_entries WHERE category = id);
```

The `WHERE category = id` if fully referenced would be `WHERE todo_entries.category = categories.id` as is the case with dart Select functions with joins.

I have run the above drift generated sql statement against the todos.db directly from DBBrowser for SQLite and it returns all three categories. The following statement returns the expected two categories medium and low (excluding the important category which has one entry against it).

```sql
SELECT * FROM categories WHERE NOT EXISTS (SELECT * FROM todo_entries WHERE todo_entries.category = categories.id);
```

**Comment by simolus3** [comment]
Nice report, thanks a lot for analyzing the problem and the explanation!

I've fixed this in 81c59c0b99cc1e1ca0610bbc66714a6b8dc1bbd7. In the meantime, you can work around this problem by using a `JoinedSelectStatement` for the inner query, e.g.

```dart
notExistsQuery(selectOnly(todos)
  ..addColumns([todos.id])
  ..where(todos.category.equalsExp(categories.id)))
```
