### ISSUE TITLE
Nested transactions

### ISSUE THREAD

**Issue by simolus3** [simolus3/drift#1904]
Currently, using a `transaction` block in an existing `transaction` will just re-use the outer transaction. This can be confusing if the inner transaction call throws an exception that is caught in the outer transaction, as it is now unclear how many statements made it through:

```dart
await transaction(() async {
  // some statements
  try {
    await transaction(() async {
      // more statements
      await someOperationThatMightFail();
      // even more statements
    });
  } on FailedOperationException {
    // ...
  }

  // At this point, we have no way of knowing how far the inner transaction got
});
```

It would be a lot less surprising if the inner transaction was atomic as well, so that it either completes or fails entirely. In sqlite3, we can emulate nested transaction by using `SAVEPOINT`, `RELEASE` and `ROLLBACK TO` instead of `BEGIN`, `COMMIT` and `ROLLBACK`, respectively. Drift could be doing that behind the scenes to support nested transactions. I've started to work on that in 8def7055a09ea1b403edca22e591e6352b2b50aa, but more work is needed to fully support that:

- [x] Support nested transactions through isolates and web workers
- [x] Support nested transactions in `drift_sqflite`
- [x] Support nested transactions in the FFI/wasm-based implementations
- [x] Support nested transactions in the sql.js-based implementation (probably works, needs tests) 
- [x] Document nested transactions on the website

**Comment by simolus3** [comment]
@westito I think it would be great if we could support nested transactions for postgres as well, but I couldn't quite figure out how.

I tried removing the transaction executor from the postgres package to just send the `BEGIN` statements manually (using a `NoTransactionDelegate()` which also takes care of nested transactions now). But the database just seems to close when the `BEGIN` statement is sent and I couldn't figure out why. Does anything come to mind to you?

**Comment by westito** [comment]
Postgres works like sqlite above: BEGIN; SAVEPOINT xxx; ROLLBACK TO  xxx; RELEASE xxx; COMMIT;/ROLLBACK;

**Comment by simolus3** [comment]
Yeah that's the same as sqlite, but when I tried the same implementation (with those commands being managed by a `NoTransactionDelegate`), all of the tests failed because the database connection was suddenly reported to be closed. Maybe it's a bug in `package:postgres`, I'll check again.

**Comment by simolus3** [comment]
I think it's an issue with `package:postgres`: https://github.com/isoos/postgresql-dart/issues/43
