### ISSUE TITLE
Stream does not fire after a batch transaction has inserted data(in isolate)

### ISSUE THREAD

**Issue by DennisMuchiri** [simolus3/drift#1906]
@simolus3 I'm experiencing a weird issue where i set up a stream after clearing a table; the streams fires first time with an empty result list since my select statement returns a stream of rows. After batch inserting data into the table, the stream does not fire.
how I clear the table
```
try { 
await getIt<AppDatabase>() .deleteCacheDatabaseData();
 } catch (e) { 
logger.d(e.toString()); 
}
```

deleteCacheDatabaseData function

```
Future<void> deleteCacheDatabaseData() async { 
await customStatement('PRAGMA foreign_keys = OFF'); 
var _isDeleteAll = await transaction(() async { 
for (var table in allTables) { 
if (table.actualTableName == Constants.storedfsdbos) { 
await delete(table).go(); 
}else{ continue; 
} 
}
 });
 await customStatement('PRAGMA foreign_keys = ON'); return _isDeleteAll; 
}

```

Batch transaction that inserts data

```
Future insertAllStoredfsdbosCompanion( 
List<StoredfsdbosCompanion> storedfsdbosCompanionList, ) 
async { 
return await batch((b) { 
 b.insertAll( storedfsdbos, storedfsdbosCompanionList, );
 });
 }
```

Please help.

**Comment by simolus3** [comment]
I tried to reproduce this with an example in drift that essentially

- adds some rows to a table
- uses your delete function to clear that table in a transaction
- then adds some more rows in a batch

However, this seems to work fine and a query stream is updated after the batch as well.

<details>
<summary>Changes to example in drift</summary>

```patch
diff --git a/drift/example/main.dart b/drift/example/main.dart
index f26af054..5aead96a 100644
--- a/drift/example/main.dart
+++ b/drift/example/main.dart
@@ -73,19 +73,6 @@ class Database extends _$Database {
     return MigrationStrategy(
       onCreate: (m) async {
         await m.createAll();
-
-        // Add a bunch of default items in a batch
-        await batch((b) {
-          b.insertAll(todoItems, [
-            TodoItemsCompanion.insert(title: 'A first entry', categoryId: 0),
-            TodoItemsCompanion.insert(
-              title: 'Todo: Checkout drift',
-              content: const Value('Drift is a persistence library for Dart '
-                  'and Flutter applications.'),
-              categoryId: 0,
-            ),
-          ]);
-        });
       },
     );
   }
@@ -96,28 +83,50 @@ class Database extends _$Database {
   // In drift, queries can be watched by using .watch() in the end.
   // For more information on queries, see https://drift.simonbinder.eu/docs/getting-started/writing_queries/
   Stream<List<TodoItem>> get allItems => select(todoItems).watch();
+
+  Future<void> deleteCacheDatabaseData() async {
+    await customStatement('PRAGMA foreign_keys = OFF');
+    var _isDeleteAll = await transaction(() async {
+      for (var table in allTables) {
+        if (table.actualTableName == 'todo_items') {
+          await delete(table).go();
+        } else {
+          continue;
+        }
+      }
+    });
+    await customStatement('PRAGMA foreign_keys = ON');
+    return _isDeleteAll;
+  }
+
+  Future insertAllStoredfsdbosCompanion(
+    List<TodoItemsCompanion> storedfsdbosCompanionList,
+  ) async {
+    return await batch((b) {
+      b.insertAll(
+        todoItems,
+        storedfsdbosCompanionList,
+      );
+    });
+  }
 }
 
 Future<void> main() async {
   // Create an in-memory instance of the database with todo items.
-  final db = Database(NativeDatabase.memory());
+  final db = Database(NativeDatabase.memory(logStatements: true));
+  await db.todoCategories
+      .insertOne(TodoCategoriesCompanion.insert(name: 'foo'));
 
   db.allItems.listen((event) {
     print('Todo-item in database: $event');
   });
 
-  // Add category
-  final categoryId = await db
-      .into(db.todoCategories)
-      .insert(TodoCategoriesCompanion.insert(name: 'Category'));
-
-  // Add another entry
-  await db.into(db.todoItems).insert(TodoItemsCompanion.insert(
-      title: 'Another entry added later', categoryId: categoryId));
-
-  (await db.select(db.customViewName).get()).forEach(print);
-  (await db.select(db.todoCategoryItemCount).get()).forEach(print);
+  await db.todoItems
+      .insertOne(TodoItemsCompanion.insert(title: 'title', categoryId: 1));
+  await db.deleteCacheDatabaseData();
 
-  // Delete all todo items
-  await db.delete(db.todoItems).go();
+  await db.insertAllStoredfsdbosCompanion([
+    TodoItemsCompanion.insert(title: 'after 1', categoryId: 1),
+    TodoItemsCompanion.insert(title: 'after 2', categoryId: 1),
+  ]);
 }
```
</details>

One thing that stands out are the foreign keys. Are you sure that there's no foreign key conflict when you turn them back on in the transaction? If there is one, there may be an exception that gets lost somewhere? That could explain the batch not running.

Either way, I need more information to check what's going on here since a repro inside an example from this repository seems to work.

**Comment by DennisMuchiri** [comment]
@simolus3 I don't have foreign keys in the database.

My  Stream query


  Stream<List<Storedfsdbo>>
  getStoredfsdboServiceProvidersByVerticalId(
      List<String> _verticalIds,
      ) {
    String TAG = 'getStoredfsdboServiceProvidersByCategoryNameAndVerticalId:';
    var query =
    (select(storedfsdbos)).join([])
      ..orderBy([
        OrderingTerm(
            expression: storedfsdbos.sptradingname, mode: OrderingMode.asc),
      ])
      ..groupBy([storedfsdbos.sptradingname])
      ..where(storedfsdbos.sptradingname.isNotNull() &
      storedfsdbos.uicategory.isNotNull() &
      storedfsdbos.verticalonlineid.isNotNull() &
      storedfsdbos.verticalonlineid
          .lower()
          .isIn(_verticalIds.map((e) => e.toLowerCase()).toList()));

    return query.watch().map<List<Storedfsdbo>>((typedData) {
      return typedData.map((onetypedData) {
        return onetypedData.readTable(storedfsdbos);
      }).toList();
    });
     
  }
  
  My table
  
  import 'package:drift/drift.dart';

class Storedfsdbos extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get onlineid => text().customConstraint('UNIQUE')();
  TextColumn get name => text()();
  TextColumn get description => text()();
  DateTimeColumn get datetimeCreated => dateTime().nullable()();
  DateTimeColumn get lastModified => dateTime().nullable()();
  TextColumn get status => text().nullable()();

  TextColumn get spk => text()();
  TextColumn get sponlineid => text()();
  TextColumn get sptradingname => text()();

  TextColumn get typename => text()();
  TextColumn get typeonlineid => text()();
  TextColumn get typek => text()();

  TextColumn get verticalname => text()();
  TextColumn get verticalonlineid => text()();
  TextColumn get uicategory => text().nullable()();
  DateTimeColumn get devicesyncedrequestvalidatorat => dateTime().nullable()();
}

**Comment by DennisMuchiri** [comment]
@simolus3 forgot to tell you that the batch insert happens in an isolate

**Comment by simolus3** [comment]
Is the query stream running in one isolate and the batch runs in another? This requires special setup, drift needs to make the two isolates communicate for query streams to work in that case ([docs on isolates](https://drift.simonbinder.eu/docs/advanced-features/isolates/)).

**Comment by DennisMuchiri** [comment]
@simolus3 true. After many tests and extra reference to the documentation, I have configured a dart isolate that supplies a connection to all threads. In my other isolates i pass it's send port and from that i am able to make a database connection. It is now firing the streams as expected. Thank you. Closing
