### ISSUE TITLE
How to apply inner join for four tables? 

### ISSUE THREAD

**Issue by pranay2210** [simolus3/drift#360]

**Comment by simolus3** [comment]
You you just use
```dart
select(firstTable).join([
  innerJoin(secondTable, condition),
  innerJoin(thirdTable, condition),
  innerJoin(fourthTable, condition),
])
```
Do you need anything special I'm missing?

**Comment by pranay2210** [comment]
Could you please provide me an example so that I could find it more clear to use. Thank you

**Comment by DougSiqueira** [comment]
> You you just use
> 
> ```dart
> select(firstTable).join([
>   innerJoin(secondTable, condition),
>   innerJoin(thirdTable, condition),
>   innerJoin(fourthTable, condition),
> ])
> ```
> 
> Do you need anything special I'm missing?

And when I have three many-to-many relationships and one to many relationships. How to make this inner join?

**Comment by DougSiqueira** [comment]
It is related to my problem: 
#345

**Comment by simolus3** [comment]
@pranay2210 Can you describe your scenario some more? Like what kind of tables you have and what query you need. If I know more about your use case I can write a fitting example.

**Comment by dickermoshe** [comment]
I'm closing `question` issues that are older than a year.
This is one of them.
