### ISSUE TITLE
How to query a list inside a json

### ISSUE THREAD

**Issue by manojbcs98** [simolus3/drift#408]
int varietyId;
"data": {
      "varieties": [
        4,
        5
      ],
}

Here i need to query all the entries where varietyId is present inside the "varieties" list. How can this be done?

**Comment by simolus3** [comment]
The best way to use this would be a query in a [moor file](https://moor.simonbinder.eu/docs/using-sql/moor_files/). You'll also need to enable the json1 extension in your [builder options](https://moor.simonbinder.eu/docs/advanced-features/builder_options/#available-extensions).

You could do something like
```sql
import 'path/to/your/table/classes.dart';

findWithVariety(:variety AS INT): SELECT table.* 
  FROM table, json_each(json_extract(table.json_column, '$.data.varieties')) varieties
WHERE :variety IN varieties
```

Moor will then generate a `Selectable<DataClass> findWithVariety(int variety)` method which you can `get()` or `watch()`.

Note that json1 is only available when using `moor_ffi`.

**Comment by manojbcs98** [comment]
Instead of querying in Moor file cant be done in DAO file?
If it can be done in DAO file how it would be?

**Comment by simolus3** [comment]
At the moment this can't be done in Dart. `json_extract` essentially returns a new table, which is not supported by the Dart api at the moment. Supporting table-valued functions in Dart would probably be a large and complicated change.

**Comment by rodydavis** [comment]
Is it possible to have the generated classes return the list for the type?

Since varieties is a List<String> how would the table look with json_extract in a drift file?

**Comment by simolus3** [comment]
I should mention that `json_each` is now available in the Dart query builder as well, so the issue should be addressed with that. The last example [in this section](https://drift.simonbinder.eu/docs/dart-api/select/#json-support) is using JSON joins as a filter.

> Is it possible to have the generated classes return the list for the type?

Do you mean when something based on `json_each` or `json_extract` is used as a result column in a query? If you can write a type converter for the inner field, you can apply it to the result column with `MAPPED BY`, like [shown here](https://drift.simonbinder.eu/docs/sql-api/drift_files/#type-converters) for example.

**Comment by rodydavis** [comment]
Yep that's what I ended up doing (MAPPED BY) and worked well 👍🏼
