### ISSUE TITLE
Handling complex data models in moor

### ISSUE THREAD

**Issue by pranay2210** [simolus3/drift#417]
We have 3 tables in our moor DB as follows:

itemMaster ==> (itemID, itemType, itemCategory, status, grossWt)
stoneMaster ==> (stoneID, stoneType, stoneColour, stoneCarats)
itemStoneMapping ==> (itemID, stoneID, stoneCount)

Each item can be mapped to more than one stone and each stone can be mapped to more than one item

I have created 2 model object for the Item and Stone tables as follows

class Stone {
int stoneID;
String stoneType;
String stoneColour;
String stoneCarats;
float carats
}

class Item {
int itemID;
String itemType;
String itemCategory;
String status;
double grossWt;
List<Stone> stones
}

When fetching a list of items, I might want to filter out the items that have a particular stoneType. For this when I construct an instance of the Item class, I want it to contain instances of all the stones that it has been mapped to.
What would be the best way to achieve this?

**Comment by simolus3** [comment]
> Each item can be mapped to more than one stone and each stone can be mapped to more than one item

The `itemStoneMapping` table seems reasonable for this, but I wonder what `stoneCount` is doing in there?

> For this when I construct an instance of the Item class, I want it to contain instances of all the stones that it has been mapped to.

We have an example for many-to-many relationships like the one you're describing in [the documentation](https://moor.simonbinder.eu/docs/examples/relationships/#selecting-a-cart), does that help?

**Comment by dickermoshe** [comment]
I'm closing `question` issues that are older than a year.
This is one of them.
