### ISSUE TITLE
Many-to-many multiple times?

### ISSUE THREAD

**Issue by perojas3** [simolus3/drift#422]
So I have an 3 entities, the first that posses a many to many relationship with the second one , and the second one have a many-to-many relationship with the third one.
I have seen the example of the many-to-many in the documentation, but what about doing it multiple times?
I thought about doing multiple queries, but I'm not sure.
What do you recomend?

**Comment by DougSiqueira** [comment]
This topic can help you:
https://github.com/simolus3/moor/issues/345

**Comment by simolus3** [comment]
> I thought about doing multiple queries, but I'm not sure.

It depends on what you're trying to load. For instance, let's say you have `A <-> B <-> C` where `<->` is a many-to-many relationship. If you now want to load all rows from `C` that are in a transitive relationship with `A`, one simple query would be enough.
If you want to load everything from A, B and C including their relationships, you'd need multiple queries.
