### ISSUE TITLE
do you have plans something similar to '@Relation in Android Room'?

### ISSUE THREAD

**Issue by wph144** [simolus3/drift#522]
guide is in this link
https://developer.android.com/reference/android/arch/persistence/room/Relation

It is great feature on Android Room.
I guess it's somewhat complex but really convenient because it reduce many join syntax when tables have many 1:1 or 1:N relationship.

**Comment by m-azyoksul** [comment]
Any comments on this? It is an essential feature in my opinion. I would really appreciate it.

No comments for way over a year makes mee sad.

**Comment by simolus3** [comment]
So far I don't have plans for this. It would require turning a single select stream into multiple select streams that update atomically. The generator has some initial support to transform select statements at build time (which could be used to implicitly add joins for 1:N relations), but I'm not sure if this is something that moor should do.

**Comment by mt-akar** [comment]
@simolus3 thank you for responding.

>but I'm not sure if this is something that moor should do.

I strongly disagree. Every single ORM I have ever used (EF Core, Room, etc.) had this feature. In my opinion, this is why ORMs even exist: to eliminate boilerplate code. If writing [this](https://stackoverflow.com/a/68551236/7279624) just to get data from a single relation makes sense to you, just wait until  I need to write [this ](https://gist.github.com/mt-akar/03092235b55e47f9d7eca9bac92b6d15) query.

**Comment by dickermoshe** [comment]
@mt-akar The Manager API has added this in 2.18
