### ISSUE TITLE
SqliteException: variable number must be between ?1 and ?999, SQL logic error

### ISSUE THREAD

**Issue by bakua** [simolus3/drift#524]
Hello,

select queries in SQLite are limited to have 999 value subtitutions with ?. So if I know I'll be doing something line `select * from table whenere id IN :ids;` then I have to make sure to batch such query by 999 ids. As this is a boilerplate, is that something that could be generated by Moor in advance?

**Comment by simolus3** [comment]
I'm not sure what's the best way to approach this. Generating multiple selects with subsets of the list sounds fragile when we have multiple list parameters.

Maybe we can implicitly do something like this:
```sql
CREATE TEMP TABLE tmp_list_arg_01 (arg INTEGER /* or the matching type */);
INSERT INTO tmp_list_01 (?); -- with ? = ids[0]
...
select * from table where id in tmp_list_arg_01
DROP TABLE tmp_list_arg_01
```

Running the `insert` a lot shouldn't be a problem as it writes to memory and we can easily cache the prepared statement.

**Comment by bakua** [comment]
Agree on fragility with multiple list statements, Interesting solution you have there. I wonder what the performance would be. Could you try?

**Comment by dickermoshe** [comment]
I'm closing `question` issues that are older than a year.
This is one of them

**Comment by simolus3** [comment]
Recent sqlite versions also support more variables, so this should be resolved or at least be less of a problem today.
