### ISSUE TITLE
Store & use dates with millisecond precision

### ISSUE THREAD

**Issue by ened** [simolus3/drift#662]
I would like to store dates in millisecond precision, e.g. `2020-06-25 12:23:01.814536`.

Sqlite supports multiple data types for operating on dates as stated in https://www.sqlite.org/datatype3.html; so it should be possible to transparently handle this using their [functions](https://www.sqlite.org/lang_datefunc.html).

In our App, the database definition now contains:

```
  DateTimeColumn get date => dateTime()();
```

Which defaults to unix timestamp according to the docs:

> A column that stores a [DateTime]. Times will be stored as unix timestamp and will thus have a second accuracy.

From my point of view, there are two solutions:
- Store the timestamp in text and adjust ANY query to handle it manually using the functions above (storing in text probably means I'd need to run the data through a date function in order to make it comparable)
- See if moor can have built in support for different types of accuracy 😄 

A proposal could be the introduction of a DateTimeAccuracy.SECONDS enum, to be used like so:

```
DateTimeColumn get date => dateTime().withAccuracy(DateTimeAccuracy.SECONDS)();
DateTimeColumn get date => dateTime().withAccuracy(DateTimeAccuracy.MILLISECONDS)();
DateTimeColumn get date => dateTime().withAccuracy(DateTimeAccuracy.DAYS)();
```

Depending on the accuracy chosen, Moor could then use different column types under the hood and do all the functions transparently to the user.

**Comment by eprafulla** [comment]
If you are looking to build a local moor cache for Azure Table Storage records synchronizing on Timestamp, we are sailing in the same boat :) 
Azure Table Storage Timestamp go to 7th decimal places for accuracy of seconds. You round anything from this and Timestamp synchronization falls apart. Planning to use the Text column workaround for the time. Not sure how max() is going to react to a string field.

**Comment by simolus3** [comment]
If I remember correctly, some datetime functions from sqlite3 only work on seconds (see also https://github.com/simolus3/moor/issues/215).

If you just want to store `DateTime`s without using moor's builtin functions on them, you can always use a `TypeConverter` between `int` and `DateTime` that stores them with milli or microsecond accuracy.

> Not sure how max() is going to react to a string field.

It will compare strings alphabetically, which can yield unexpected results for numeric values.

> A proposal could be the introduction of a DateTimeAccuracy.SECONDS enum

An issue is that the functions working on time in sql all take an `Expression<DateTime>`, so they can't know the accuracy. 

I'll see if I can come up with a more accurate representation of time that would be opt-in so it isn't breaking. But getting the next release out has a higher priority for me at the moment.

**Comment by simolus3** [comment]
In drift 2.0, it will be possible to store datetime values as text (https://github.com/simolus3/drift/issues/286). In this mode, drift essentially calls `toIso8601String()` which preserves milliseconds (tested for you in a735e91f30a3b977c5c2b94bdffe4ed1451e12bb). Note that calling sqlite3's date time transformation functions will still loose milliseconds (that's a limitation in sqlite3), but for simple queries that don't modify date time values in SQL, the accuracy is kept.
