### ISSUE TITLE
GroupBy Date?

### ISSUE THREAD

**Issue by NightOwlCoder** [simolus3/drift#698]
Hey there, first let me say you package is great, I'm really enjoying working with it, but now I'm stuck.

Suppose I have this table:

``` dart
class Rows extends Table {
  IntColumn get id => integer().autoIncrement()();
  DateTimeColumn get date => dateTime()();
```

I want to count records, grouped by date, something like:

``` sql
select strftime('%Y-%m'-%d, DateColumn) dt, count(*) number 
from row 
group by dt;
```

But after 3 hours, I gave up.
How can I write this with moor?
Any hints?

**Comment by simolus3** [comment]
This should work:

```dart
Expression<String> date(Expression<DateTime> time) {
  return FunctionCallExpression('date', [time]);
}

// Then, you can query like this
final formattedDate = date(rows.date);
final rowCount = countAll();

final query = db.selectOnly(db.todosTable)
  ..addColumns([formattedDate, rowCount])
  ..groupBy([formattedDate]);

return query.map((row) {
  final date = row.read(formattedDate); // a String
  final amount = row.read(rowCount); // an int

  // todo: Use columns
});
```

The `selectOnly` method is used when we don't care about all columns from a table. You can also check the docs on [group by in moor](https://moor.simonbinder.eu/docs/advanced-features/joins/#group-by) for more information.

**Comment by mschmidm** [comment]
This still works today, but since drift stores DateTimes as unix timestamps by default, we must pass the modifier argument “unixepoch”. Without this, the function would always return null.
```
Expression<String> date(Expression<DateTime> time) {
  return FunctionCallExpression('date', [time, const Constant<String>('unixepoch')]);
}
```

**Comment by simolus3** [comment]
The [date](https://drift.simonbinder.eu/api/drift/datetimeexpressions/date) extension is also available on `Expression<DateTime>` since recent drift versions, so the function call doesn't have to be created manually. That also has the benefit of working when date times are stored as text.
I'll close this issue since I think the extension should cover this well enough and enable group by operations as well.
