### ISSUE TITLE
batch update?

### ISSUE THREAD

**Issue by rodriger06** [simolus3/drift#782]
Hi Team,

i was wondering if there is a batch version for update. for example, i am using batch insert as follow

  Future<void> insertMultipleEntries(List<IncomeCompanion> income2) async{
    await batch((batch) {
      batch.insertAll(income, income2);
    });
  }

income is my table name and income2 is my list of income.
this insert is working nice.

now, I have a List of income with different values in their fields(every income in the list is unique) and i want to be able to do a batch update.
how do i perform the batch update?  i could not find updateAll batch procedure.  can someone show me how to do?
i dont want to loop for all element in the list and all the update function to update.

thanks in advance

**Comment by simolus3** [comment]
> i dont want to loop for all element in the list and all the update function to update

Why not? That's a valid approach to solve this. Multiple statements don't have much of a performance impact in a `batch`. In fact, methods like `insertAll` also use a `for` loop internally.

If every income in the list is unique, you might be able to use [`replaceAll`](https://pub.dev/documentation/moor/latest/moor/Batch/replaceAll.html).

**Comment by rodriger06** [comment]
Thanks for the quick response. Can you give me an example of how to call
replaceAll?  I updated moor to the latest version in pubspec.yaml and call
replace all like this: update(income).replaceAll(dataList)

This is giving me an error: the method replaceAll isn't defined for the
type update statement

I will appreciate if you can show me how to call replaceAll. Am I doing
something wrong?

Thanks

**Comment by simolus3** [comment]
Inside a batch, you have to use

```dart
await batch((batch) {
  batch.replaceAll(income, dataList);
});
```

**Comment by dickermoshe** [comment]
I'm closing `question` issues that are older than a year.
This is one of them.
