### ISSUE TITLE
use CASE WHEN IN MOOR

### ISSUE THREAD

**Issue by Ahmed-elshorbagy** [simolus3/drift#806]
How to effeciently implement multiple case when in moor to mimic this sql
```
SELECT trackid,name
CASE
             WHEN milliseconds<60000    THEN
                 'short'
              When milliseconds>60000 And milliseconds<300000 THEN 'medium'
              ELSE   'long'
              END category
FROM tracks;
```
Thanks in advance

**Comment by simolus3** [comment]
We don't (yet) support `CASE` from the Dart query builder. Of course, you can use `CASE` expressions in [custom queries](https://moor.simonbinder.eu/docs/using-sql/custom_queries/) or [moor files](https://moor.simonbinder.eu/docs/using-sql/moor_files/).

In your case, you're only using the `CASE` expression in a result column, so you might as well implement this in Dart:

```dart
final result = select(tracks).map((track) {
  String category;
  if (track < 60000) {
    category = 'short';
  } else if (track < 300000) {
    category = 'medium';
  } else {
    category = 'long';
  }
  
  // ...
}).getAll();
```

**Comment by simolus3** [comment]
Must have missed this issue - [caseMatch](https://pub.dev/documentation/drift/latest/drift/Expression/caseMatch.html) has been available for some time.
