### ISSUE TITLE
create indices without .moor file

### ISSUE THREAD

**Issue by jackple** [simolus3/drift#868]
Is there a plan for creating indices like:
```dart
@override
Set<Column> get index => {group, user};
```

**Comment by ycherniavskyi** [comment]
@simolus3 could you please explain creating index in code in more detail.

Because I could not find such `Index` class as in your example. I could find only [this]( https://pub.dev/documentation/moor/latest/moor/Index-class.html).

**Comment by simolus3** [comment]
@ycherniavskyi That was just an api suggestion, it's not implemented yet.

If you want to define an index without moor files, you could use something like this today:

```dart
class YourDatabase extends _$YourDatabase {
  // ...

  @override
  Iterable<SchemaEntity> get allSchemaEntities {
    return [
      ...super.allSchemaEntities,
      Index('my_index', 'CREATE INDEX my_index ON  ...'),
    ];
  }
}
```

**Comment by ycherniavskyi** [comment]
Aha, I see.

@simolus3 and thank you for your suggestion, I like it more than which I come with 😊:
```dart
class YourDatabase extends _$YourDatabase {
  // ...

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (m) async {
      await m.createAll();
      await m.createIndex(Index('my_index', 'CREATE INDEX my_index ON ...'));
    },
    // ...
  );
}
```

**Comment by Ashok-Varma** [comment]
@ycherniavskyi @simolus3 

what about something similar to room. 
```kotlin
@DataClass(
  tableName = 'user',
  indices = arrayOf(
    Index(value = ["last_name", "address"]),
    Index(value = ["first_name", "last_name"], unique = true)
  )
)
data class User(
    @PrimaryKey val id: Int,
    @ColumnInfo(name = "first_name") val firstName: String?,
    @ColumnInfo(name = "last_name") val lastName: String?,
    @Ignore var picture: Bitmap?
)

```

**Comment by FMorschel** [comment]
It's been more than two years since the last comment here. 

I would like to show my support for this feature as well!

**Comment by simolus3** [comment]
Thanks for the reminder. I've implemented support for this on `develop`, the next drift version will support indices defined in Dart.

The syntax I had in mind for that is an annotation on the table to specify the columns in the index:

https://github.com/simolus3/drift/blob/8300782662333ba78f5eb83605508ac2c7893515/drift/example/main.dart#L15-L24

Of course, the annotation can be repeated to add multiple indices on the same table, and an index can also be made unique. Let me know if you have a use case that can't be expressed with this API, thanks!
